### ISSUE TITLE
prettyplease strips comments

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wit-bindgen#1086]
As of https://github.com/bytecodealliance/wit-bindgen/pull/971 which switches wit-bindgen's Rust bindings to use `prettyplease`, the "DO NOT EDIT" and "Options used:" comments no longer appear in the generated output. For example, in the hello-wasi-http example, the diff looks like [this](https://github.com/sunfishcode/hello-wasi-http/pull/18/files#diff-c030113407a164cbd1ad3500c613f59abd4346ba13ee5b653c56f393c937b0a8L1):

```diff
--- a/src/bindings.rs
+++ b/src/bindings.rs
@@ -1,5 +1,3 @@
-// Generated by `wit-bindgen` 0.25.0. DO NOT EDIT!
-// Options used:
 #[allow(dead_code)]
 pub mod wasi {
     #[allow(dead_code)]
```

I debugged this and found that the comments are getting stripped [here](https://github.com/bytecodealliance/wit-bindgen/blob/main/crates/rust/src/lib.rs#L1101) where prettyplease is invoked.

@yoshuawuyts

**Comment by morenol** [comment]
Related to this https://github.com/dtolnay/prettyplease/issues/50

**Comment by sunfishcode** [comment]
Thanks! That's useful context. To work around that, I've now submitted #1087 to avoid running the comments through prettyplease.
