### ISSUE TITLE
Recursive Types

### ISSUE THREAD

**Issue by theduke** [bytecodealliance/wit-bindgen#114]
Recursive types are not currently supported, but would be very nice to have.

I'd probably be able to work on this if the feature is welcome.

**Comment by alexcrichton** [comment]
I commented [here](https://github.com/bytecodealliance/wit-bindgen/issues/115#issuecomment-993688848) as well but this may be a discussion best had on the interface types repository rather than here

**Comment by theduke** [comment]
Understood.

I'll comment here: https://github.com/WebAssembly/interface-types/issues/137
