### ISSUE TITLE
rust-wasm export cannot find imported handle types

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wit-bindgen#120]
This repository:

https://github.com/sunfishcode/import-export-demo

contains a wit-bindgen project which imports provider.wit:
```wit
resource thing {
    frob: function()
}
```
and exports runner.wit:
```wit
use { thing } from provider

doit: function(it: thing)
```

in a simple Rust program:
```rust
wit_bindgen_rust::import!("provider.wit");
wit_bindgen_rust::export!("runner.wit");

struct Exports;

impl runner::Runner for Exports {
    fn doit(it: provider::Thing) {
        it.frob()
    }
}
```

It currently gets this error:

```
$ cargo build --target=wasm32-wasi
   Compiling import-export-demo v0.0.0 (/home/sunfish/import-export-demo)
error[E0412]: cannot find type `Thing` in module `super`
 --> src/lib.rs:2:1
  |
2 | wit_bindgen_rust::export!("runner.wit");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `super`
  |
  = note: consider importing this struct:
          crate::provider::Thing
  = note: this error originates in the macro `wit_bindgen_rust::export` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `Runner` in module `super`
 --> src/lib.rs:2:1
  |
2 | wit_bindgen_rust::export!("runner.wit");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `super`
  |
  = note: consider importing this trait:
          crate::runner::Runner
  = note: this error originates in the macro `wit_bindgen_rust::export` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `Runner` in module `super`
 --> src/lib.rs:2:1
  |
2 | wit_bindgen_rust::export!("runner.wit");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `super`
  |
  = note: this error originates in the macro `wit_bindgen_rust::export` (in Nightly builds, run with -Z macro-backtrace for more info)

```
Looking at the code in gen-rust, I see methods like `handle_in_super` and `handle_projection` which look like they're related to this, but it's not clear to me what they need to do here.

**Comment by Cyborus04** [comment]
Looking at it with `cargo expand`, it looks like the expanded code makes no reference to "provider" (how would it know where it is?) so would it possible to define the expected imports in the macro? i.e.:
```rust
wit_bindgen_rust::export!("runner.wit", "provider::thing" = provider::Thing);
```
or
```rust
wit_bindgen_rust::export!("runner.wit", provider { "thing" = provider::Thing });
```
I'm not too well versed in proc-macros so I'm not sure how this would be implemented

**Comment by alexcrichton** [comment]
In general resources-in-other-modules isn't really well supported in probably any of the bindings generators right now. This is something I haven't really devoted much thought to and figured we'd fix things later as they came up and became more imporant. Basically to say that this is largely unimplemented right now and that's expected.

As for things like `handle_projection` that's for import/export distinctions where sometimes resources are projected associated types from a trait and other times they're a locally defined type. 

I think we'd probably want to first decide how this should look in Rust and it presumably wouldn't be too too hard to implement the generator afterwards.

**Comment by Liamolucko** [comment]
> so would it possible to define the expected imports in the macro? i.e.:
> 
> ```rust
> 
> wit_bindgen_rust::export!("runner.wit", "provider::thing" = provider::Thing);
> 
> ```
> 
> or
> 
> ```rust
> 
> wit_bindgen_rust::export!("runner.wit", provider { "thing" = provider::Thing });
> 
> ```

I think that's a good idea, but it might be simpler to just reference the module as a whole, e.g.:

```rust
wit_bindgen_rust::export!("runner.wit", "provider" = some_crate::some_module::provider);
```

**Comment by alexcrichton** [comment]
I'm going to close this in favor of https://github.com/bytecodealliance/wit-bindgen/issues/266 as I'm trying to consolidate all of these various issues about the same problem.
