### ISSUE TITLE
Mutability support

### ISSUE THREAD

**Issue by fabricedesre** [bytecodealliance/wit-bindgen#121]
First, congrats for this project! It provides a nice middle ground between the very opinionated wasm-bindgen and hand rolling everything.

I'm experimenting with using `wit-bindgen` to expose image manipulation algorithms. Simplifying a bit, the main function signature looks like:
```
process_image: function(algorithm: string, data: list<u8>, width: u32, height: u32) -> option<list<u8>>
```
Where data is an array of RGBA pixels.

From the web side, the `data` is a `Uint8ClampedArray` which comes from a `ImageData.data`. It is possible in JS to just mutate this array, which is much more memory efficient, but I don't see a way to achieve that with `wit-bindgen` (basically expecting a `&mut Vec<u8>` instead of a `Vec<u8>`.

Is there any blocker to this kind of support? If not, how would we proceed to add this capability?

**Comment by alexcrichton** [comment]
Currently this isn't really supported in the model of interface types. The closest "approximation" is to work with `resource` handles which refer to memory effectively owned by someone else. Doing things fancier than that, though, can get difficult. This is part of the interface-types model, however, so to implement extensions here I think it would be better to first discuss improvements in the interface-types repository.

**Comment by fabricedesre** [comment]
Ok, thanks @alexcrichton . I'll play around with `resource` handles first!
