### ISSUE TITLE
Multi-value returns are undocumented

### ISSUE THREAD

**Issue by Liamolucko** [bytecodealliance/wit-bindgen#140]
Looking at this test:

https://github.com/bytecodealliance/wit-bindgen/blob/48f364d1d4e42275b219d0862af8aa8b17c49d51/tests/codegen/simple-functions.wit#L8

It seems like there's some kind of multi-value return support which isn't documented in WIT.md. The parser also accepts stuff like:

```wit
foo: function() -> (bar: string, baz: s32, u8)
```

This should probably be documented, or removed if it isn't supposed to be there.

**Comment by alexcrichton** [comment]
Ah this is intentional syntax I believe I just forgot to document.

**Comment by alexcrichton** [comment]
The new canonical ABI doesn't support multiple return values so I'm going to close this in favor of https://github.com/bytecodealliance/wit-bindgen/issues/201 since this will be a removed feature
