### ISSUE TITLE
Fields with Option types in JS don't use optional `?` syntax

### ISSUE THREAD

**Issue by willemneal** [bytecodealliance/wit-bindgen#147]
Currently the types generated for optional interface properties use `| null`, however, there is an optional syntax of `field?: T`, which is short hand for `T | undefined`.

If this was not done for a particular reason, I'd love to make a PR to make this change.  From a DevX perspective it's better because you don't have to provide a null value when using the type. E.g.

```ts
interface Foo {
  optional: string | null
  other?: string
}

let f: Foo = {optional: null}
let foo: Foo = {} // <--- Type error since the `optional` field is missing.
```

**Comment by alexcrichton** [comment]
Ah the usage of `string | null` was just the first thing I reached for, I agree that using TS-native things like `other?: string` is much better, and a PR to do this would be most welcome!

**Comment by willemneal** [comment]
Great! Will do!
