### ISSUE TITLE
Converter .webidl -> .wit ?

### ISSUE THREAD

**Issue by munrocket** [bytecodealliance/wit-bindgen#149]
Is it planned to create .idl -> .wit converter? It seems that it can be useful to focus only on this .wit format and get js glue and webidl together (for languages that didn't implemented webidl integration yet).

**Comment by alexcrichton** [comment]
Can you clarify what ".idl" format you're referring to? Do you meant WebIDL? Or perhaps some other idl of some kind?

**Comment by munrocket** [comment]
Yes, WebIDL, here an example of it https://hg.mozilla.org/mozilla-central/file/tip/dom/webidl/WebGLRenderingContext.webidl

**Comment by alexcrichton** [comment]
Ah ok, at this time there are no plans for this, but it's something that I think would be worthwhile at some point. There's tons of WebIDL for the web and having some way to interoperate that with interface types is highly desired. I don't know the exact shape this would take but it probably won't precisely be a `*.webidl` to `*.wit` converter, I think there's a lot of other various subtelties which need to be handled, probably with a specific JS glue layer or something like that.

**Comment by alexcrichton** [comment]
I'm going to close this for now as there's no immediate plans to implement this, but I think it's still going to eventually be wanted for JS hosts where it's a nice way to give components access to web APIs. Whether or not it's specifically a WebIDL to `*.wit` converter, though, I'm not sure.
