### ISSUE TITLE
Plans to publish parser?

### ISSUE THREAD

**Issue by willemneal** [bytecodealliance/wit-bindgen#157]
I know this project isn't stable, but was wondering if the parser could be published, or at least a part of it.

This would allow for other tooling that use wit outside of its original intention.  It's not a huge issue as I've already published a fork.

**Comment by alexcrichton** [comment]
It is intended that this will all be published eventually but for now we're holding off while things are unstable. Once it's a bit more stable though these will be on crates.io

**Comment by willemneal** [comment]
Great thanks!
