### ISSUE TITLE
`handle ...` -> `handle<...>`

### ISSUE THREAD

**Issue by badeend** [bytecodealliance/wit-bindgen#164]
I suggest changing the `handle` syntax to use angle brackets for consistency with other types that take type parameters: `expected<...>`, `tuple<...>`, `option<...>`, `list<...>`

Example: `handle my-resource` -> `handle<my-resource>`

**Comment by alexcrichton** [comment]
I think the eventual intention is to remove `handle` altogether as `handle my-resource` can also be replaced with `my-resource`. If it sticks around though I think it makes sense nowadays to use brackets to enclose the name.

**Comment by kulakowski-wasm** [comment]
Alex, I was looking around at other gardening tasks in wit-bindgen re component model syntax changes. Luke suggested I ask you:

1. Can this issue be closed?
2. Should [the CM description of the syntax](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#keywords) be changed to remove `handle` as a keyword, or is there a reason to keep it reserved?
3. ditto but for the `wit-parser` lexer

**Comment by alexcrichton** [comment]
Yeah I think this can be closed. I forget the precise status of the keyword in parsing, but I do think we should remove it entirely and then fixup the AST/etc as necessary to keep the examples working.
