### ISSUE TITLE
Implement the new canonical ABI

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wit-bindgen#201]
I've started sending PRs to do this, but I figured it'd also be a good thing to write things down:

* [ ] Implement and test NaN canonicalization for float32/float64
* [ ] Make a plan for string encodings -- hardcode to utf-8? option-per-language?
* [ ] Enable mutability in Rust traits generated for in-wasm since recursive entry is now prohibited (#178)
* [ ] [Use `post-return` instead of individual `free` calls](https://github.com/bytecodealliance/wit-bindgen/pull/310)
* [x] [Update cases in variants to require their type payload](https://github.com/bytecodealliance/wit-bindgen/pull/220)
* [x] [Add a `union` type](https://github.com/bytecodealliance/wit-bindgen/pull/219)
* [x] [Add an `option` type](https://github.com/bytecodealliance/wit-bindgen/pull/215)
* [x] [Add an `expected` type](https://github.com/bytecodealliance/wit-bindgen/pull/215)
* [x] [Add an `enum` type](https://github.com/bytecodealliance/wit-bindgen/pull/211)
* [x] [Add a `tuple` type](https://github.com/bytecodealliance/wit-bindgen/pull/210)
* [x] [Add a `flags` type](https://github.com/bytecodealliance/wit-bindgen/pull/209)
* [x] [Change return-multiple-values ABI](https://github.com/bytecodealliance/wit-bindgen/pull/207)
* [x] [Implement MAX_FLAT_PARAMS for passing arguments](https://github.com/bytecodealliance/wit-bindgen/pull/208)
* [x] [Remove support for old-style `*.witx`](https://github.com/bytecodealliance/wit-bindgen/pull/195)
* [x] [Remove support for `char8` and `usize`](https://github.com/bytecodealliance/wit-bindgen/pull/197)
* [x] [Rename `f32` and `f64` to `float32` and `float64`](https://github.com/bytecodealliance/wit-bindgen/pull/198)
* [x] [Change the `variant` ABI w.r.t. the "join" function](https://github.com/bytecodealliance/wit-bindgen/pull/199)
* [x] [Split out the `string` type from `list<char>`](https://github.com/bytecodealliance/wit-bindgen/pull/202)
* [x] [Add a `bool` type ](https://github.com/bytecodealliance/wit-bindgen/pull/204)
* [x] [Add a `unit` type](https://github.com/bytecodealliance/wit-bindgen/pull/204)
* [x] [Remove support for multiple return values](https://github.com/bytecodealliance/wit-bindgen/pull/206)

(I'll probably add to this over time as I remember things)

**Comment by alexcrichton** [comment]
I'm going to close this in favor of https://github.com/bytecodealliance/wit-bindgen/issues/314 since the remaining few items here and there that need to be covered by hosts I think require deeper refactorings to fully address or they're inconsequential to not really matter a whole lot.

**Comment by dbaeumer** [comment]
@alexcrichton I have a question regarding (since all the 'favored' issues are closed)

> Enable mutability in Rust traits generated for in-wasm since recursive entry is now prohibited

wit-bindgen version 0.24.0 still generates `x(&self)` signature in traits. Is this going to change in the future.

**Comment by alexcrichton** [comment]
It can theoretically yeah but it would be a bit of a nontrivial lift. I didn't handle that during this whole transition due to the complexity involved, but I forgot to open another tracking issue. If you're up for it would you be ok opening a new issue for it?
