### ISSUE TITLE
Failure with _ types

### ISSUE THREAD

**Issue by ramnivas** [bytecodealliance/wit-bindgen#225]
I am trying to run wit-bindgen over the cache.wit file from https://radu-matei.com/blog/intro-wasm-components/.

It does work fine if I install the32e63116d469d8046727fae3c1333a7d35d0c5d3 revision (as mentioned in the blog post), but not if I install the current main branch producing an error that it found an `_` when a type was expected. Since the 32e63116d469d8046727fae3c1333a7d35d0c5d3 revision is already merged into `main`, I wonder if this is a regression.

```
> cargo install wit-bindgen-cli --git https://github.com/bytecodealliance/wit-bindgen --rev 32e63116d469d8046727fae3c1333a7d35d0c5d3

> wit-bindgen wasmtime --export cache.wit                                                                                           
Generating "bindings.rs"

> cargo install wit-bindgen-cli --git https://github.com/bytecodealliance/wit-bindgen

> wit-bindgen wasmtime --export cache.wit                                             
Error: expected a type, found keyword `_`
     --> cache.wit:14:43
      |
   14 | delete: function(key: string) -> expected<_, error>
      |                                           ^
```

Here is a minimized wit file to reproduce the issue:
```
delete: function() -> expected<_, _>
```

And the full cache.wit file for reference:
```
// Type for cache errors.
enum error {
    runtime-error,
    not-found-error,
}
// Payload for cache values.
type payload = list<u8>
// Set the payload for the given key.
set: function(key: string, value: payload, ttl: option<u32>) -> expected<_, error>
// Get the payload stored in the cache for the given key.
get: function(key: string) -> expected<payload, error>
// Delete the cache entry for the given key.
delete: function(key: string) -> expected<_, error>
```

**Comment by theduke** [comment]
_ was replaced with the explicit `unit` type.

**Comment by ramnivas** [comment]
Thanks for the clarification. I have made a PR (https://github.com/bytecodealliance/wit-bindgen/pull/226) to reflect this in the format documentation.

**Comment by Aeledfyr** [comment]
`_` is still referenced in the [Types section](https://github.com/bytecodealliance/wit-bindgen/blob/de91e00e906b932c1f8c5715acd28f52b94fe8b5/WIT.md#types) of the grammar documentation:

```
expected ::= 'expected' '<' expected-ty ',' expected-ty '>'
expected-ty ::= '_'
              | ty
```
