### ISSUE TITLE
Update `WIT.md` to use `func` keyword instead of `function`

### ISSUE THREAD

**Issue by eyebrowsoffire** [bytecodealliance/wit-bindgen#236]
I have been familiarizing myself with the .wit format, and playing around with it in the online bindings generator. One thing I noticed is that the `WIT.md` grammar and examples all use the keyword `function`, but that doesn't actually work in the bindings generator, it uses the keyword `func`. I'm not sure if the documentation is out of date and the implementation is correct, or the other way around, but it would be good if these two things matched up.

**Comment by peterhuene** [comment]
It just changed to `func` very recently, so there's probably places where we failed to update the examples. If you spot any, we'd happily take a PR!

**Comment by eyebrowsoffire** [comment]
Oh it actually *just* updated. I was using a newer version of the online bindings generator but reading a version of `WIT.md` from yesterday! That being said, I did find that the grammar itself uses the wrong string, so I did open a PR: https://github.com/bytecodealliance/wit-bindgen/pull/238

**Comment by peterhuene** [comment]
Thanks again for putting up a fix for this issue!
