### ISSUE TITLE
update online demo to use func instead of function

### ISSUE THREAD

**Issue by attacker0211** [bytecodealliance/wit-bindgen#237]
https://bytecodealliance.github.io/wit-bindgen/

**Comment by peterhuene** [comment]
Hi @attacker0211. Thanks for reporting this. wit-bindgen recently changed the `function` keyword to `func`, but it appears the online playground wasn't updated.

#238 should fix this shortly.

**Comment by peterhuene** [comment]
This should now be resolved. Thanks!
