### ISSUE TITLE
Unable to use underscore in identifier

### ISSUE THREAD

**Issue by MarkintoshZ** [bytecodealliance/wit-bindgen#251]
I wonder why using the underscore character in identifiers is not allowed here.
```
debug_function: func()
```
gives the following error
```
invalid character in identifier '_'
     --> input:1:1
      |
    1 | debug_function: func()
      | ^
``` 
Also, where could I find the formal definition for .wit files?

**Comment by MarkintoshZ** [comment]
Thank you. That makes sense.

**Comment by Kylebrown9** [comment]
For now, you can reference the [WIT.md](https://github.com/bytecodealliance/wit-bindgen/blob/main/WIT.md) file in this repo
