### ISSUE TITLE
Wit-bindgen support for zero-level exports

### ISSUE THREAD

**Issue by kulakowski-wasm** [bytecodealliance/wit-bindgen#264]

**Comment by sunfishcode** [comment]
It isn't in the component-model repo yet, but the idea is that it's an anonymous export. In a component that only exports one thing, it avoids the need to name it. And a component with a zero-level export wouldn't be able to have any other non-zero-level exports, so it'd be a way to encode "this component only exports this one thing".

**Comment by kulakowski-wasm** [comment]
We opened this issue because we were considering having preview2 depend on this idea, but decided not to in the end. Future discussion of zero-level exports will happen in the component model repo.
