### ISSUE TITLE
Improve `wit-component` help

### ISSUE THREAD

**Issue by tsoutsman** [bytecodealliance/wit-bindgen#274]
`wit-component -h` lists the `-i` flag as "the default interface of the component". Looking through the source code, this seems to be the default **exported** interface of the component. It'd be good to disambiguate the description of the flag. If I'm correct, I'd be happy to submit a quick PR to fix the issue.

**Comment by peterhuene** [comment]
@tsoutsman you are correct. Happy to review and merge your PR!
