### ISSUE TITLE
Automatically generate *.wit bindings

### ISSUE THREAD

**Issue by hamza1311** [bytecodealliance/wit-bindgen#282]
Automatically generate `*.wit` bindings from any language, like Rust.

It becomes tedious (or borderline impossible) to manually write bindings for any kind of complex code. This is already a well-known (and solved) problem when it comes to generating C-bindings. In the Rust ecosystem, [`cbindgen`](https://github.com/eqrion/cbindgen) crate aims to solve this.

### Additional Context

I initially brought this up in the Zulip about a week ago ([message link](https://bytecodealliance.zulipchat.com/#narrow/stream/327223-wit-bindgen/topic/Create.20bindings.20from.20rust.20code/near/289095298)) but received no response. 

Initial message (which also contains context of the problem I attempted to solve):

> Hi, I'm thinking of using wit to export a Rust API from one crate and import it in another. The API is the Yew components. I would like to have a WASM package that exports those components and another package that imports them. Is it possible?
> 
> Example of component: https://github.com/yewstack/yew/blob/5570710cdf88658877b0ddc41e4b531cd7bdc7e6/examples/counter_functional/src/main.rs
> `cargo expand` output: https://gist.github.com/hamza1311/61aaa9974825574ff066a3169de3b677
> 
> When importing, the `BaseComponent` impl is needed so it can be consumed: https://api.yew.rs/next/yew/virtual_dom/struct.VComp.html#method.new

Since then, I've looked through some of the code and couldn't find any way to automatically generate bindings

**Comment by alexcrichton** [comment]
While I think this might be valuable to investigate one day for now this is out of scope of this project. We might eventually come back around to investigate this but at this time our hands are full enough implementing the component-model as is so I'm going to close this. The general hope is that in the steady-state future `*.wit` files are managed by only a few folks and are really all that prevalent so it ideally won't be the case that everyone is maintaining a second `*.wit` file on the side.
