### ISSUE TITLE
Did `wasmlink` Move Again?

### ISSUE THREAD

**Issue by zicklag** [bytecodealliance/wit-bindgen#298]
Hey there!

I'm looking for wherever https://github.com/peterhuene/wasmlink went, if it still exists.

I'm trying to link a WASM module compiled from C with a WASM module compiled from Rust, and be able to call the C functions from Rust.

**Comment by alexcrichton** [comment]
`wasmlink` was removed in https://github.com/bytecodealliance/wit-bindgen/pull/240 as it's being replaced by the component model. It was historically used for different purposes of possibly polyfilling the component model but a different route is being taken for that now.

**Comment by peterhuene** [comment]
@zicklag [wasm-compose](https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-compose) will offer some of `wasmlink`'s functionality, namely being able to compose a component from other components. The remaining functionality of generating adapter code has been supplanted with support for the component model proposal in Wasmtime itself.

Currently the `wasm-compose` example is all Rust, but it shouldn't be that difficult to use current `wit-bindgen` to replace one of the components with an implementation in C.

I'm currently working on improving `wasm-compose` for general use.

**Comment by zicklag** [comment]
Awesome, thank you both for your links and quick responses!
