### ISSUE TITLE
[c-api] How does one correctly index with the pointer returned from a an exported function with c-api? 

### ISSUE THREAD

**Issue by f3lixding** [bytecodealliance/wit-bindgen#303]
Currently trying to experiment with coming up with my own bindgen code for interfacing with functions imported from WASM in a host written in c. 

This is my .wit file for a hello world function:
```
hellotwo: func(name: string) -> string
```

From looking at the output of `cargo expand` on the guest package, I understand that the return of this function is a `i32` denoting the index on the module's linear memory that contains the address of the return turned into a byte array, the length of which is written in the next byte over:
```
let ptr1 = __GUESTTWO_RET_AREA.0.as_mut_ptr() as i32;
        let vec2 = (result.into_bytes()).into_boxed_slice();
        let ptr2 = vec2.as_ptr() as i32;
        let len2 = vec2.len() as i32;
        core::mem::forget(vec2);
        *((ptr1 + 4) as *mut i32) = len2;
        *((ptr1 + 0) as *mut i32) = ptr2;
        ptr1
```

I was able to verify that the length information is present and correct, however, when I try looking up what the pointer in ptr1 contains, they are null:

```
// addr as i32: %c: %d
1054992: �: 208          <-- ptr2 (1054992 is ptr1)
1054993: 0: 48
1054994: : 16
1054995: : 0
1054996: : 24             <-- len2 (this is correct) 

// if we look up what 208 indexes:
// addr as i32: %c: %d
208: : 0
209: : 0
210: : 0
211: : 0
212: : 0
213: : 0
214: : 0
215: : 0
216: : 0
217: : 0
...
```

I printed the entire block and I was able to see the return present. However, I am struggling to understand how I am supposed to obtain this address, or what it has to do with what was returned (ptr1). 

[See relevant files here](https://gist.github.com/f3lixding/45e208b5dcccd1a29a23e6a66402238f)

Any help is appreciated. Thank you so much.

**Comment by Liamolucko** [comment]
`ptr2` isn't the individual byte pointed at by `ptr1`, it's the first 4 bytes starting from that one, encoded as a little-endian 32-bit integer. So, in this example, the correct pointer is `0 << 24 + 16 << 16 + 48 << 8 + 208 << 0 = 1061072`.

**Comment by f3lixding** [comment]
Oh that makes sense. 
I have made the following changes
```
uint32_t ret_addr = 0;
  for (int i = 0; i < 4; i++) {
    // little-endian, starting at the end
    uint32_t cur_byte = ptr0[ret_ptr0_loc + 3 - i] << (ret_len - (8 * i));
    ret_addr += cur_byte;
  }
```

And it works. Thank you so much!
