### ISSUE TITLE
Support (@witx repr u16) format for enums

### ISSUE THREAD

**Issue by fschutt** [bytecodealliance/wit-bindgen#323]
Currently the code generator can only generate `u8` bitflags for enums. This is a problem because when migrating from .witx to .wit, we cannot port any enum flags. Is `repr u16`, `repr u32`, etc. going to be supported or how should this be ported?

**Comment by alexcrichton** [comment]
It's not intended that support will be added for this at this time. The representation of enums is defined with the canonical abi in the [component-model repository](https://github.com/webassembly/component-model) and isn't something that wit-bindgen is at the liberty of modifying.

The representation of an enum is also not always `u8`. If there are more than 256 variants then `u16` is chosen to fit the variant. More details can be found in that repository.
