### ISSUE TITLE
Canonical ABI-based memory manipulation / value population from the host

### ISSUE THREAD

**Issue by philpax** [bytecodealliance/wit-bindgen#324]
Hi there!

I was wondering if wit-bindgen had any plans to provide an API for manipulation of the guest's memory using the WIT-defined types, so that more complex APIs than are currently expressible in WIT (e.g. generics) can be built through other means.

---

As a specific example: I am trying to expose an entity-component system across the boundary, and would like to offer an efficient query mechanism where the guest can specify components to query, the host will execute the query, and then populate memory specified by the guest with the data of the components.

The API for this on the guest will look something like:
`query7<T, U, V, W, X, Y, Z>: tuple<T, U, V, W, X, Y, Z> -> list<tuple<T, U, V, W, X, Y, Z>>` (with multiple implementations over N parameters)

This is not currently possible to represent in wit-bindgen as there are no support for generics, nor am I expecting there to be (it's a hard problem to solve!), but I'd still like to do this.

The way I envision this working is something like:
1) The guest code runs a pre-query against the host that retrieves the number of results. (`query7-pre(t, u, v, w, x, y, z) -> (query-id, usize)`)
2) The guest allocates an output list of tuples, then passes the pointer to the data to the host through another call (`query-populate(query-id, output-buffer)`)
3) The host side of that call then retrieves the data and populates the output buffer accordingly using this canonical ABI mechanism. The host knows the types of the components, so no need to communicate that. The host does something like `(T, U, V, W, X, Y, Z)::write(&mut memory, address)` for each row of the result.
4) The call completes, and the guest now has a populated list.

---

As a simpler example of something that I am currently working around: each time my guest executes, it requires some context. I would prefer to drive the guest through a WIT-provided guest function, but this is not currently possible due to #293 / #266.

Instead, I am populating a global memory variable on the guest with the required context, which the guest then reads. At present, I'm doing this by copying the host's C ABI representation into the guest, which is *very* hacky and will only work where the host's ABI matches the canonical ABI.

I would prefer to use a WIT type to write into the guest's memory from the host, and to have the guest read the variable correctly. The functionality I've described here would be sufficient to satisfy this need - that is, defining a structure in my `.wit`, populating it on the host, and then writing it into the guest's memory with `wit-bindgen` provided machinery.

---

Please let me know if this requires any clarification; I'd be happy to disambiguate anything if required. For both of these cases, we currently have workarounds, but we'd like to resolve both of these sooner to remove any potential performance / correctness hazards.

Thanks once again for all of the help and the great work so far!

**Comment by alexcrichton** [comment]
I think the short answer to this is that it's not supported and likely won't be, but I can try to elaborate on that as well. In terms of generics and features there, that's best a question for the component-model repository rather than this repository since wit-bindgen is trying more nowadays to pivot to "just implement the component model". 

For example in the component model a component cannot export a linear memory, meaning that embedders have no raw access to linear memory since the component cannot export it. This means that the manipulation you're talking about here I don't believe will be possible.

**Comment by alexcrichton** [comment]
I think that'd probably be best for the component model repo. For me personally I'm focused on trying to get what's here in a shippable state.

**Comment by philpax** [comment]
Gotcha, thanks!
