### ISSUE TITLE
How to replace the `custom_error` feature

### ISSUE THREAD

**Issue by Maaarcocr** [bytecodealliance/wit-bindgen#435]
in https://github.com/bytecodealliance/wit-bindgen/pull/355 the `custom_error` flag was removed. Is there any substitute for such feature in the newer versions on wit-bindgen? Is this now unnecessary? If so, why? 

If there is a plan to add something like this back, I would also be happy to spend some time trying to get it done!

**Comment by alexcrichton** [comment]
Pat's working on error-handling for wit-bindgen by prototyping this first in wiggle as part of https://github.com/bytecodealliance/wasmtime/pull/5276 and https://github.com/bytecodealliance/wasmtime/pull/5279 and I believe he plans on carrying over that work to this repository in short order.

**Comment by pchickey** [comment]
Yep I have the PR half-done right now, it should be up today or tomorrow

**Comment by Maaarcocr** [comment]
Thank you!!

**Comment by alexcrichton** [comment]
Looking back I think this was more-or-less done in https://github.com/bytecodealliance/wit-bindgen/pull/388 where Wasmtime-hosted functions by default return `anyhow::Result<T>` now where `T` is the result of the function and all other errors are traps. For `result<_, _>`-returning functions in `*.wit` that now translates to `Resul<T, Error<E>>` where `Error<E>` can be created from `E` or from `anyhow::Error` (more-or-less) where the former represents something to return to the guest and the latter represents a trap. You can implement custom `From<MyType> for Error<E>` conversions to weave custom errors into an `E` as necessary.
