### ISSUE TITLE
gen-guest-c: optional parameters with null pointers

### ISSUE THREAD

**Issue by guybedford** [bytecodealliance/wit-bindgen#451]
In the C guest generator, functions which have optional parameters of the form:

```
x: func(a: option<a>, b: option<b>) -> _
```

Currently output signatures like:

```c
void interface_x(interface_option_a_t *a, interface_option_b_t *b);
```

Where it would be nice to support the more C-like interface:

```c
void interface_x(interface_a_t *a, interface_b_t *b);
```

where a null pointer could be used to imply the optional parameter value instead.

**Comment by guybedford** [comment]
As far as I can tell, implementation here would require that `OptionLift` and `OptionLower` operations have additional information in core indicating if they are parameters that are being lifted or lowered, so the special casing can apply.

**Comment by alexcrichton** [comment]
I think that may not be necessary since the context of a generator fixes that, e.g. for C when generating an imported call lifts only happen for results. So given the context of import or export, and C, I think that designates what's being lowered and what's being lifted.

**Comment by guybedford** [comment]
I think this might still be necessary actually, as when defining an imported function one ends up with a wrapper looking like the following:

```c
void fn (float *maybe_a, float *maybe_b) {
  interface_option_float_t a;
  a.is_some = maybe_a != NULL;
  if (maybe_a) {
    a.val = *maybe_a;
  }
  if (a.is_some) {
    //... logic...
    option = 1;
    option1 = *payload0;
  } else {
    option = 0;
    option1 = 0;
  }
```

where my concern is that we end up copying the data out of the pointers in this approach when perhaps we should be optimizing this?

For what it is worth, I hit up against similar issues in the JS generator.

Alternatively I can just implement the wrapper approach as described above for now, leaving the door open to further optimizations in future to remove the extra copy.

**Comment by alexcrichton** [comment]
Ah this is something I think it safe to optimize for later. The set of data possibly being extraneously loaded per call would be a small enough fixed size that I doubt this'd ever be an issue. If it is an issue we could try adding `restrict` or w/e corresponding attributes C has for "this doesn't alias" or things like that.

**Comment by guybedford** [comment]
Ok, I'll work to the above for now.

**Comment by guybedford** [comment]
Landed in https://github.com/bytecodealliance/wit-bindgen/pull/453.
