### ISSUE TITLE
guest-rust: UB in `cabi_realloc`

### ISSUE THREAD

**Issue by lann** [bytecodealliance/wit-bindgen#464]
In `cabi_realloc`:

https://github.com/bytecodealliance/wit-bindgen/blob/98c2b1e4cb10d3757114b7524d112511a4c7459e/crates/guest-rust/src/lib.rs#L28-L37

If `old_len > 0` and `new_len == 0`, you'll end up calling `alloc::realloc(..., 0)`.

> https://doc.rust-lang.org/std/alloc/trait.GlobalAlloc.html#method.realloc
>
> ... undefined behavior can result if the caller does not ensure all of the following:
> ...
> - new_size must be greater than zero.

**Comment by lann** [comment]
I imagine this isn't _really_ UB since we know the underlying `realloc` contract.

**Comment by lann** [comment]
Actually, it isn't clear to me what `cabi_realloc` _should_ do if `old_len > 0 && new_len == 0`. Some allocators treat it as a `free`.

**Comment by alexcrichton** [comment]
I think we can statically say that won't happen in the component model, but it would nonetheless be good to have an assertion just in case perhaps?
