### ISSUE TITLE
Online demo not parsing example wit file

### ISSUE THREAD

**Issue by joepio** [bytecodealliance/wit-bindgen#467]
The demo at https://bytecodealliance.github.io/wit-bindgen/ shows this without editing anything:

```
expected '.', found keyword `default`
     --> input:8:3
      |
    8 |   default export interface {
      |   ^
```

It has to do with the [default .wit file](https://github.com/bytecodealliance/wit-bindgen/blob/98c2b1e4cb10d3757114b7524d112511a4c7459e/crates/wit-bindgen-demo/index.html#L37), which does not currently parse. This could be a parsing bug. Anyways, I think it would be better to use a `.wit` example that is guaranteed to work, e.g. something that's synced with the examplre

**Comment by joepio** [comment]
Since the [online demo might be removed soon](https://github.com/bytecodealliance/wit-bindgen/pull/463#issuecomment-1404280827), perhaps looking into this issue isn't worth it.

**Comment by alexcrichton** [comment]
Yes this is getting removed in https://github.com/bytecodealliance/wit-bindgen/pull/463 so I'm going to close this, but thanks for the report though!
