### ISSUE TITLE
Update readme to describe new JS host binding generation process

### ISSUE THREAD

**Issue by robertlong** [bytecodealliance/wit-bindgen#468]
I just started looking into wit-bindgen yesterday and tried generating some bindings for use in JS. The instructions here say to use ` wit-bindgen host js --import example.wit` however doing so yields an error:

```
> wit-bindgen host js --import example.wit
error: unexpected argument '--import' found

  note: to pass '--import' as a value, use '-- --import'

Usage: wit-bindgen host js [OPTIONS] <COMPONENT>

For more information, try '--help'.
```

I dug a little further and found [this issue](https://github.com/bytecodealliance/wit-bindgen/pull/463) which led me to [js-component-tools](https://github.com/bytecodealliance/js-component-tools).

So for those stumbling down the same path as me trying to generate some JS host bindings, take a look at js-component-tools.

**Comment by alexcrichton** [comment]
Thanks for the report! I've got an updated README ready-to-go once https://github.com/bytecodealliance/wit-bindgen/pull/463 lands since the repository has shifed so much in the meantime.
