### ISSUE TITLE
Embed the version of wit-bindgen in generated files

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wit-bindgen#487]
Following up on @Mossaka's idea in #486, we should add a comment to generated source files indicating the wit-bindgen version, for debugging purposes.

**Comment by pchickey** [comment]
My plan was to add a producers section to the wasm inside the `component-type` section, so that the version of wit-bindgen carried through to the final artifact. Of course, we can also make a string available in the generated code.
