### ISSUE TITLE
How to use wit-bindgen in build.rs?

### ISSUE THREAD

**Issue by lz1998** [bytecodealliance/wit-bindgen#489]

**Comment by lz1998** [comment]
> Sorry I am not sure if I undersatnd the question. Could you please elaborate more on what scenarios are you using `wit-bindgen` in build.rs?
> 
> If you wish to run wit-bindgen-cli in `build.rs`, you can totally do that with `std::process::Command::new("wit-bindgen");` and then feed in the argument to indicate what guest language to produce the bindings and what WIT file.
> 
> If you wish to run embed `wit-bindgen` in `build.rs`, you can check out the the use of `WorldGenerator` in "codegen.rs" and the test-helper crate.

I hope to use wit-bindgen like [prost](https://github.com/tokio-rs/prost). When I run `cargo check`, it will generate code in the `target` dir automatically.

```rust
use std::path::{Path, PathBuf};
fn recurse_dir(v: &mut Vec<PathBuf>, dir: impl AsRef<Path>) {
    for entry in
        std::fs::read_dir(&dir).unwrap_or_else(|_| panic!("Unable to read dir: {:?}", dir.as_ref()))
    {
        let path = entry.expect("Unable to get direntry").path();
        if path.is_dir() {
            recurse_dir(v, path);
        } else if let Some(true) = path.extension().map(|v| v == "proto") {
            v.push(path);
        }
    }
}
fn main() {
    let mut files = Vec::new();
    recurse_dir(&mut files, "src/pb");
    prost_build::compile_protos(&files, &["src/pb"]).unwrap();
}
```

**Comment by alexcrichton** [comment]
For a Rust guest, are you unable to use the procedural macro `generate!`? If not, that's the way to generate code. If so, can you detail more why it won't work for you?

**Comment by fuxiaohei** [comment]
https://github.com/fuxiaohei/leaf-wasm/blob/main/build.rs#L27
https://github.com/fuxiaohei/leaf-wasm/blob/main/crates/compiler/src/lib.rs#L14

this is your case? I generate guest rust code from wit file in build.rs. code is from wit-bindgen cli.

**Comment by alexcrichton** [comment]
Sorry but I'm confused. This looks like an example of a generator that doesn't live in this repository? It also looks like it's being used from `build.rs`? Does something about that not work? Are you otherwise using one of the generators in this repository and having trouble with it?

**Comment by alexcrichton** [comment]
Oh sorry @fuxiaohei I was a bit too tired this morning and didn't notice that that you were proposing a solution, I mistakenly thought you opened the issue!

@lz1998 is that a problem with all procedural macros and IDEs? Would @fuxiaohei's solution work for you?
