### ISSUE TITLE
Cargo does not find wit-bindgen-guest-rust

### ISSUE THREAD

**Issue by Giom-fm** [bytecodealliance/wit-bindgen#511]
Hello,

I have a problem adding wit-bindgen-guest-rust. Cargo does not seem to find the crate.
I use the following command as shown in the readme:

```
cargo add --git https://github.com/bytecodealliance/wit-bindgen wit-bindgen-guest-rust
    Updating git repository `https://github.com/bytecodealliance/wit-bindgen`
error: the crate `wit-bindgen-guest-rust@https://github.com/bytecodealliance/wit-bindgen` could not be found at `https://github.com/bytecodealliance/wit-bindgen`
```
Am I missing something?

**Comment by alexcrichton** [comment]
Thanks for the report! This was a bug in the README now fixed, but the crate is called `wit-bindgen` now.

**Comment by Giom-fm** [comment]
Its running again!
Thanks
