### ISSUE TITLE
C Optional Flattening in Foreign

### ISSUE THREAD

**Issue by Mossaka** [bytecodealliance/wit-bindgen#524]
For the following interfaces 

```Go
interface a {
	record t2 { a: u32 }
	type t7 = option<t2>
}
  
interface the-interface {
	use self.a.{ t7 as u7, t2 as u2 }
	f2: func(a: u2) -> u2
	f7: func(a: u7) -> u7
}
  
default world foo {
	use self.a.{ t7 as u7 }

	export f7: func(a: u7) -> u7

	import the-import: self.the-interface
	export the-export: self.the-interface
}

```

The generated C header file looks like this

```C
typedef struct {
  uint32_t a;
} a_t2_t;

typedef struct {
  bool is_some;
  a_t2_t val;
} a_t7_t;

typedef a_t7_t the_import_u7_t;

typedef a_t2_t the_import_u2_t;

typedef a_t7_t foo_u7_t;

typedef a_t7_t the_export_u7_t;

typedef a_t2_t the_export_u2_t;

// Imported Functions from `the-import`
void the_import_f2(the_import_u2_t *a, the_import_u2_t *ret);
bool the_import_f7(the_import_u7_t *a, a_t2_t *ret);
```

It looks like the optional flattening will use the renamed type `the_import_u2_t` but instead uses the original type name `a_t2_t`. I am not sure what's the right behaviour here. Would love to hear your ideas. @alexcrichton @guybedford

**Comment by alexcrichton** [comment]
This isn't necessarily intentional and is fine to change. Option stuff came way before interfaces and use.

As a side note, one idea I just had is to add an option to the C generator to disable all flattening like this and generate a more "raw" interface. It might be worth exploring what that would look like maintainability wise

**Comment by guybedford** [comment]
I tend to agree having a first-class direct interface would be a good idea, for this generator especially.

Another way to look at the distinction between raw and usable bindgen might be defining usable bindgen in terms of wrappings of raw bindgen. Then raw bindgen with direct low-level options as the base layer. At least that was my hope for the JS generation as well.

**Comment by Mossaka** [comment]
I don't know if this much effort of making a first-class direct interface for C is worth it considering the Go bindgen depending on C bindgen is a temperory solutation that eventually will be removed in favor of building a Wasm ABI bindgen for Go. But I can see value in it especially if we want to have more generators based on the C bindgen.

**Comment by Mossaka** [comment]
Close this one as #534 removes flattening on Go bindgen
