### ISSUE TITLE
Offer option to disable generation/use of borrowed types for Rust

### ISSUE THREAD

**Issue by philpax** [bytecodealliance/wit-bindgen#535]
G'day again!

Under certain scenarios, `wit-bindgen` (and Wasmtime, which uses similar machinery) will use borrowed types instead of owned types for arrays and strings. This works fine when it's for single-level owned types, like `String -> &str` or `Vec<u8> -> &[u8]`.

Unfortunately, having nested owned types - like `Vec<String>` - results in the borrowed equivalent being `&[&str]`, which is quite tedious to work with, especially with converting it back and forth to the owned representation.

In our project, I've had to define [a macro](https://github.com/AmbientRun/Ambient/blob/e96a252355b823b1a4ea8a834c8ac7a3dce15c17/crates/wasm/src/shared/borrowed_types.rs) to generate intermediate types to convert the owned representation of [our value variant type](https://github.com/AmbientRun/Ambient/blob/e96a252355b823b1a4ea8a834c8ac7a3dce15c17/crates/wasm/wit/component.wit#L8-L68) (as seen in #526) to the borrowed representation. This requires allocations, which feels like it defeats the purpose of borrowing to begin with.

To alleviate this, one of the following solutions would work for me (in order of bluntness):

1) Disabling the generation of borrowed types outright
2) Disabling the generation of borrowed types for a specific type
3) Limiting the generation of borrowed types to a single level, so that `Vec<String> -> &[String]` and not `&[&str]` or `Vec<&str>`.

Our current solution works fine, but it needs to be updated on both the host and the guest when new cases are added to the variant, which ends up being a bit of a maintenance hazard.

**Comment by pchickey** [comment]
Thanks. We hadn't really thought about this case, but it seems like a reasonable need. I'm fine with any of those solutions. Would you be up for implementing this?

**Comment by philpax** [comment]
Sure, I can take a look tomorrow. I'll ask if I need help, but I should be able to get the lay of the land from the recent commits that interacted with it.

**Comment by pchickey** [comment]
Thanks! Happy to answer questions here, or over on the bytecode alliance zulip.

**Comment by alexcrichton** [comment]
No worries! I personally feel that there's enough confusion around this that it's not worth it to, by default, have both modes here. I do still think it would be useful to keep it as an option, though, so I don't think the support should be completely removed yet.

To be specific I think "first layer" borrowing is still good to have too. For example `&str` vs `String`, but you'd use something like `&[String]` instead of today's `&[&str]`

**Comment by bachrc** [comment]
Bumping this too, giving parameters is really complicated, near impossible with only borrowed values.

**Comment by philpax** [comment]
I'll see if I can get around to it this week but can't make any guarantees. Might start with an option to disable borrowed type generation entirely to begin with and then look into how hard it would be for a more complicated solution.

**Comment by bachrc** [comment]
You're a life safer, don't hesitate to ping me if you need any review

**Comment by bachrc** [comment]
@pchickey you did not have to close this issue : the pull request mentioning « close #thispullrequest », when the pull request would have been merged, this issue would have been merged. Yet this issue is not fixed, the PR has been merged
