### ISSUE TITLE
[rust] macro seems confused with references to `pkg`

### ISSUE THREAD

**Issue by Fristi** [bytecodealliance/wit-bindgen#536]
In the root of my project I have a folder `wit` in there there are my wit files:

```wit
// log.wit:
default interface log {
    enum level {
        debug,
        info,
        warn,
        error
    }

    log: func(level: level, msg: string) -> ()
}

// git.wit
default world git {
  import log: pkg.log
}

```

In my `app` folder I have a rust project with `lib.rs` which uses the wit-bindgen macro:

```
wit_bindgen::generate!("git" in "../wit/git.wit");
```

However this throws an error:

```
cargo b --release --target wasm32-unknown-unknown -p app
   Compiling app v0.1.0 (/Users/markie/Projects/component-model-demo/app)
error: document `log` does not exist
            --> /Users/markie/Projects/component-model-demo/app/../wit/git.wit:67:19
             |
          67 |   import log: pkg.log
             |                   ^--
 --> app/src/lib.rs:1:1
  |
1 | wit_bindgen::generate!("git" in "../wit/git.wit");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `wit_bindgen::generate` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Depending on 0.3.0

**Comment by alexcrichton** [comment]
Thanks for the report! The issue you're running into is that if you specify a specific `*.wit` file then that single file is interpreted as a single-document package which is not what you want here. You should actually be able to remove all of the arguments from the `generate!(...)` macro invocation and I think the bindings generation should work.

**Comment by Fristi** [comment]
Ah I see, you mean literally `wit_bindgen::generate!();` ? 

With that it throws me an error:

```
error: failed to read file "/Users/markie/Projects/component-model-demo/app/wit"
       
       Caused by:
           No such file or directory (os error 2)
 --> app/src/lib.rs:1:1
  |
1 | wit_bindgen::generate!("../wit/*.wit");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `wit_bindgen::generate` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by alexcrichton** [comment]
Ah can you update to 0.4.0? I think this wasn't in 0.3.0. For the 0.3.0 version you can remove the `in "..."` I think and `wit_bindgen::generate!("git")` should work

**Comment by alexcrichton** [comment]
Can you upload an example repository to reproduce with?

**Comment by Fristi** [comment]
This is my playground project so far:

https://github.com/Fristi/witty

- Checkout `failing-pkg`
- `wit-bindgen` is on version `4.0.0` as seen here https://github.com/Fristi/witty/blob/failing-pkg/app/Cargo.toml#L13
- Run `cargo b --release --target wasm32-unknown-unknown -p app`
- It fails on https://github.com/Fristi/witty/blob/failing-pkg/wit/git.wit#L67

This is the error

```
error: document `log` does not exist
            --> /Users/markie/Projects/component-model-demo/app/../wit/git.wit:67:19
             |
          67 |   import log: pkg.log
             |                   ^--
```

**Comment by alexcrichton** [comment]
If you change it to either `wit_bindgen::generate!("git" in "../wit");` or `wit_bindgen::generate!(in "../wit");`then the `app` builds for me.

There's unfortunately not great documentation for the Rust macro right now, but it follows the same pattern as [Wasmtime's macro](https://github.com/bytecodealliance/wasmtime/blob/e64fb6ab39e75cf7bd573e20651365787a9f5bb2/crates/wasmtime/src/component/mod.rs#L50-L298), so the docs there about how to specify a world should apply to the guest rust macro here.

**Comment by Fristi** [comment]
Thanks for trying out, that also works for me!
