### ISSUE TITLE
TinyGo instructions do not work

### ISSUE THREAD

**Issue by Hpmason** [bytecodealliance/wit-bindgen#539]
There's a few parts of the instructions for TinyGo that don't work. 
1. With `tinygo build`, `-o` is the flag to control the output file
2. At least on windows, using redirection in `wasm-tools component embed --world world ./wit main.wasm > main.embed.wasm` screws up the resulting binary. Not sure if it's PowerShell being weird or if additional output is messing up the resulting `main.embed.wasm` binary. Using the `-o` flag fixes that issue.
3. Tinygo's wasm needs the additional `--adapt wasi_snapshot_preview1.wasm argument to work correctly`

**Comment by Mossaka** [comment]
Thank you!

**Comment by Hpmason** [comment]
No problem!

As for the `--adapt`, from what I can tell, tinygo doesn't support plain wasm (https://github.com/tinygo-org/tinygo/issues/3068). It's actually an issue I ran into since the component + wasi libraries in `wasmtime` are incompatible while the preview2 prototyping is happening.

I've never really touched go/tinygo before so I could be wrong about something.

**Comment by Mossaka** [comment]
I remember there is a `-target=wasm` target for compiling tinygo program to wasm running on the browser. Admittedly, I have never used it personally so I don't know much about it.

**Comment by Mossaka** [comment]
Close this since #540 has been merged
