### ISSUE TITLE
Allow runtime module to be referenced from different path in Rust macro

### ISSUE THREAD

**Issue by rylev** [bytecodealliance/wit-bindgen#564]
The Rust macro implicitly relies on `wit_bindgen` being available in the module global scope in order to call runtime functions inside of `wit_bindgen::rt`. While this makes perfect sense for direct users of the crate, this disallows using `wit_bindgen` from within another library crate's proc macro without requiring users of that macro *also* rely directly on `wit_bindgen`. 

It would be nice if there were an option for a `rt_prefix` option that works similar to the `macro_call_prefix` option that appends an arbitrary prefix to calls to the the `wit_bindgen::rt` module. By default this would be the same as today: `::wit_bindgen`. 

This would allow library authors to themselves have some sort of codegen module that looks like this:

```rust
#[doc(hidden)]
mod __codegen {
  pub use wit_bindgen;
}
```

Then in their proc macros than can use wit_bindgen like so:

```rust
::my_crate::_codegen::wit_bindgen::generate!(world: "my_world", path: "./wit", rt_prefix: "::my_crate::_codegen::wit_bindgen")
```

If this sounds like a reasonable idea, I'd be happy to implement it.

**Comment by alexcrichton** [comment]
While this seems fine to me, I'm curious to still learn more about it. For example what's the use case of wanting to invoke the `generate!` macro but not wanting to depend on `wit-bindgen` the crate? Is this something, for example, that a macro is exposed from `my_crate` doing? (if so then I'm curious what that macros is doing)

**Comment by alexcrichton** [comment]
For exports one of the intentions was that you'd generate bindings in a shared crate, e.g. the `spin` crate, and then that would export macros which a user would invoke to actually generate all the bindings. So instead of invoking `wit_bindgen::generate!` in `#[http_component]` it'd invoke `spin::export_http_handler!(..)` (I forget the precise naming). I think that'd work out for this use case still?

**Comment by alexcrichton** [comment]
And to be clear I think all the requirements around "users shouldn't have to be aware of `wit-bindgen` or WIT at all are good requirements! Definitely want to help satisfy them while keeping things working.

**Comment by rylev** [comment]
Gave the suggested approach a try and it works well enough. Feel free to close this. If I run into any unforeseen issues caused by the new approach I can open a new issue.

**Comment by alexcrichton** [comment]
Ok sounds good!
