### ISSUE TITLE
Rust `wit_bindgen::generate!` generates multiple definitions of the same type when importing with `use` and exporting the interface where the type is defined

### ISSUE THREAD

**Issue by juancastillo0** [bytecodealliance/wit-bindgen#573]
Hi, thank you so much for your work!

When using the following wit (full code https://github.com/juancastillo0/wasm_interpreter/blob/ce48f2fe0a888f097df2af3c113ab40ebf9a00c0/packages/wit_component_example/wit/types-example.wit):

```wit
default interface types-interface {
  /// a bitflags type
  flags permissions {
    read,
    write,
    exec,
  }
  ...
}

default world types-example {
    use self.types-interface.{t2 as t2-renamed, t10, permissions}
    export types-export: self.types-interface
    ...
}
```

And generating the Rust code with `wit_bindgen::generate!("types-example");` here https://github.com/juancastillo0/wasm_interpreter/blob/ce48f2fe0a888f097df2af3c113ab40ebf9a00c0/packages/wit_component_example/src/lib.rs

The macro gives the following error:
```
unused macro definition: `export_types_example`
`#[warn(unused_macros)]` on by defaultrustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B1%5D?1#file%3A%2F%2F%2FUsers%2Fjuanmanuelcastillo%2FDesktop%2Fflutter%2Fwasmi_dart%2Fpackages%2Fwit_component_example%2Fsrc%2Flib.rs)
mismatched types
struct `types_export::Permissions` and struct `types_interface::Permissions` have similar names, but are actually distinct typesrustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B2%5D?2#file%3A%2F%2F%2FUsers%2Fjuanmanuelcastillo%2FDesktop%2Fflutter%2Fwasmi_dart%2Fpackages%2Fwit_component_example%2Fsrc%2Flib.rs)
public.rs(17, 9): struct `types_export::Permissions` is defined in module `crate::types_export` of the current crate
public.rs(17, 9): struct `types_interface::Permissions` is defined in module `crate::types_interface` of the current crate
lib.rs(8, 1): the type constructed contains `types_export::Permissions` due to the type of the argument passed
option.rs(570, 5): tuple variant defined here
lib.rs(8, 1): parentheses are required to parse this as an expression: `(`, `)`
```

`cargo expand` prints the following:
https://github.com/juancastillo0/wasm_interpreter/blob/ce48f2fe0a888f097df2af3c113ab40ebf9a00c0/packages/wit_component_example/src/lib_expand.rs

`Permissions` is generated twice.

Thanks! Let me know if there is some way I can help

**Comment by alexcrichton** [comment]
Thanks for the report! This should be fixed in https://github.com/bytecodealliance/wit-bindgen/pull/574.

Note that the duplicate export of `Permissions` is intentional here, but the problem was that they weren't wired up correctly.
