### ISSUE TITLE
`std::error::Error` not implemented for wasi-sockets `ErrorCode`

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wit-bindgen#575]
wasi-sockets has an error code defined in an interface that doesn't contain a function that uses it in a result:

  - https://github.com/WebAssembly/wasi-sockets/blob/main/wit/network.wit#L27
 
It is used as the error type of a result in other interfaces, etc.:

 - https://github.com/WebAssembly/wasi-sockets/blob/main/wit/tcp.wit#L108

This appears to get past wit-bindgen's code to detect error types, so running `wit-bindgen rust wit` in that repo doesn't get `std::error::Error` implemented for the `ErrorCode` type.

**Comment by pchickey** [comment]
I encountered this the other day and I have the fix but I never turned it into a PR. Will do that this afternoon
