### ISSUE TITLE
Add `#[macro-export]` to the world export macros (eg. `export_host!`)

### ISSUE THREAD

**Issue by jakehemmerle** [bytecodealliance/wit-bindgen#595]
I haven't done much with macros, so apologies if I'm missing something fundamental here. I want to know if it's possible to use the `export_host!` macro (to quote the example) in another crate. Is it seems as simple as adding a `#[macro_export]` above it?

Specifically, the expanded `wit_bindgen::generate!("constraint")` macro that might need the `#[macro_export]`:

```rust
macro_rules! export_constraint(($t:ident) => {
  const _:() = {
    #[doc(hidden)]#[export_name = "evaluate"]#[allow(non_snake_case)]unsafe extern "C" fn __export_evaluate(arg0:i32,arg1:i32,)->i32 {
      call_evaluate::<$t>(arg0,arg1,)
    }#[doc(hidden)]#[export_name = "cabi_post_evaluate"]#[allow(non_snake_case)]unsafe extern "C" fn __post_return_evaluate(arg0:i32,){
      post_return_evaluate::<$t>(arg0,)
    }
  };
  #[used]#[doc(hidden)]#[cfg(target_arch = "wasm32")]static __FORCE_SECTION_REF:fn() = __link_section;
});
```

For context, I want richer types between the host and guest (both in Rust, and passing back and forth a struct containing a `Vec<u8>`). I'm doing `wit-bindgen::generate!("constraint");` in a package called `ec-core`, and I want to import that crate into other crates that will compile to a freestanding Wasm blob (running in wasmtime, no wasi).

The closest I've gotten so far was

```rust
pub mod bindgen {
    wit_bindgen::generate!("constraint");
    pub use export_constraint;
}
```

with the error 
```
error[E0364]: `export_constraint` is only public within the crate, and cannot be re-exported outside
 --> core/src/lib.rs:6:13
  |
6 |     pub use export_constraint;
  |             ^^^^^^^^^^^^^^^^^
  |
help: consider adding a `#[macro_export]` to the macro in the imported module
```

Thanks for your time.

**Comment by alexcrichton** [comment]
I think if you change the macro invocation to:

```rust
wit_bindgen::generate!({
    world: "constraint",
    macro_export: true,
});
```

then it should have `#[macro_export]`, but I may have gotten the syntax there slightly off

**Comment by jakehemmerle** [comment]
You rock, thanks Alex.

Correct syntax ended up being:

```rust
wit_bindgen::generate!({
    world: "constraint",
    macro_export,
});
```

and the macro is accessed from the crate root.
