### ISSUE TITLE
2nd empty instance of host trait?

### ISSUE THREAD

**Issue by jadamcrain** [bytecodealliance/wit-bindgen#597]
Hi,

I have the .wit below:

```
package battalion:plugin

interface types {
  /// One of several types of values
  variant sample-value {
     analog(float64),
     binary(bool),
     counter(u64)
  }

  /// Single sample value and tag identifier
  record sample {
      tag-id: u32,
      value: sample-value,
  }

  /// Collection of samples with a device identifier
  record samples {
      device-id: u32,
      values: list<sample>,
  }

  /// 64-bit milliseconds since start
  record delay {
      millis: u64
  }
}

/// functions required for the plugin to implement
interface guest {
  use types.{delay}

  /// Retrieve the organization that created the plugin
  org: func() -> string

  /// Retrieve the name of the plugin
  name: func() -> string

  /// Wake the plugin
  wake: func() -> option<delay>
}

/// functions required for the host to implement
interface host {
  use types.{samples, delay}

  /// publish samples to the host
  publish: func(values: samples)
}

world plugin {
  import host
  export guest
}
```

When binding in wasmtime using `bindgen!`, there are two Host traits that I have to implement. One with the `publish` function, and another empty one:

```
bindgen!(in "../../logic/wit");

#[derive(Default)]
struct PluginState {
    published: Vec<Samples>
}

impl battalion::plugin::host::Host for PluginState {
    fn publish(&mut self, samples: Samples) -> wasmtime::Result<()> {
        self.published.push(samples);
        Ok(())
    }
}

// TODO - Why is there a second host??
impl battalion::plugin::types::Host for PluginState {

}
```

The requirement to implement both can be seen in `Plugin::add_to_linker`

```
impl Plugin
pub fn add_to_linker<T, U>(linker: &mut wasmtime :: component::Linker<T>, get: impl Fn (& mut T )-> & mut U + Send + Sync + Copy + 'static) -> wasmtime::Result<()> where     U: battalion :: plugin :: types::Host + battalion :: plugin :: host::Host
```

**Question:** Why is there a 2nd empty trait (battalion::plugin::types::Host)?

Is there a better way to define my WIT to avoid this?

**Comment by pchickey** [comment]
The plugin/types interface is used transitively, so bindgen creates a trait for it, and there are no functions in that interface, so nthe trait has no members. Wit-bindgen could implement some logic to not generate those empty traits, but it does not at this time. It would probably be a good first feature to for a new contributor to implement.

**Comment by jadamcrain** [comment]
Thanks @pchickey. That makes sense, although I'm new to WASM/WIT and still fumbling.

I guess the point of confusion for me was that both traits are called `Host`. I think if one had been called `Host` and the other called `Types` it might have been more obvious what was going on here.

My goal with having a separate interface called `types` was to have some common types I use both in the `guest` and `host` interface functions. Since types can only live inside of an interface, this seemed like the only way to do this? I

**Comment by jadamcrain** [comment]
Thanks, makes sense.
