### ISSUE TITLE
Result not properly generated when empty type is used

### ISSUE THREAD

**Issue by rylev** [bytecodealliance/wit-bindgen#609]
The following wit package generates incorrect C code:

```wit
package local:demo

interface my-interface {
    variant my-error {
        some-error
    } 
    record my-record {
    }
    my-func: func() -> result<my-record, my-error>
}


world my-world {
    import my-interface
}
```

Note that the record is empty (i.e., has no fields). This leads to the generated C type to not contain the record in the union that forms the basis of the result type:

```
typedef struct {
  bool is_err;
  union {
    local_demo_my_interface_my_error_t err;
  } val;
} my_world_result_local_demo_my_interface_my_record_local_demo_my_interface_my_error_t;
```

This leads to compiler errors when trying to compile the generated code:

```
error: assigning to 'local_demo_my_interface_my_record_t' from incompatible type 'local_demo_my_interface_my_error_t'
            *ret = result.val.err;
                 ^ ~~~~~~~~~~~~~~
        1 error generated.
```

We should still be generating the record type even though it is empty.

**Comment by sunfishcode** [comment]
C requires `struct`s to occupy at least 1 byte, while the canonical ABI says that empty records should have size 0, so I imagine it's correct that we're omitting the ok field, and that just need to handle empty types more carefully when emitting the return code.

**Comment by sunfishcode** [comment]
I've now submitted #610 to fix this.
