### ISSUE TITLE
Remove `dealias` function

### ISSUE THREAD

**Issue by dicej** [bytecodealliance/wit-bindgen#630]
Per https://github.com/bytecodealliance/wit-bindgen/pull/604#discussion_r1268234625, we should consider duplicating resource type information for each of a given resource type's aliases so that we don't need to call `dealias` anywhere.  Note that we'll need to be careful to update the info for any and all aliases whenever the resource info is updated.

**Comment by alexcrichton** [comment]
I've later come to conclude that this function is necessary, so I'm going to close this.
