### ISSUE TITLE
Rust: exporting a resource results in `exports::` prefix in exported name

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/wit-bindgen#635]
For the following wit in a `wit` subdir:

```wit
package test:export-resource

world test {
    export foo: interface {
        resource x {
            constructor()
        }
    }
}
```

and the following Rust code:

```rust
wit_bindgen::generate!({
    path: "wit",
    exports: {
        "foo/x": MyX
    }
});

use exports::foo::X;

pub struct MyX;

impl X for MyX {
    fn new() -> Self {
        Self
    }
}
```

The produced module fails to componentize:

```
$ wasm-tools component new foo.wasm
error: failed to encode a component from module

Caused by:
    0: import from `[export]exports::foo` does not correspond to exported interface
```

I believe [this line](https://github.com/bytecodealliance/wit-bindgen/blob/bf318b8ae4703586ae236a232f62813efc946df3/crates/rust/src/lib.rs#L873) is adding the `exports::` prefix to the interface name.

It appears we might be relying on that for getting the proper path to the interface from the bindings source, but when generating the `#[link(wasm_import_module = "..."]` or `#[export_name = "..."]` decorators the `exports::` prefix should not be present.

**Comment by peterhuene** [comment]
cc @dicej.

**Comment by cpetig** [comment]
This reminds me of a similar problem fixed by https://github.com/cpetig/wit-bindgen/commit/18ca99c336bfb70f2047b12133c4b10a5663076d for the drop method (this patch was merged with https://github.com/bytecodealliance/wit-bindgen/pull/604 )

**Comment by cpetig** [comment]
I think this module should not import anything, so all of `struct OwnX` (which refers to the strangely named module) shouldn't be generated, the module should only export "`foo#[constructor]x`" and "`foo#[dtor]x`". (I am not sure about the hashed prefix but it is consistent with the C generator)

PS: I think the correct module for an import would be "`test:export-resource/foo`", right?
PPS: The C generator (also incorrectly?) imports from "`foo`" which is less wrong named but lacks the package prefix?
P³S: Is there a document describing the correct module and function symbol naming schema?
