### ISSUE TITLE
Example from README.md doesn't work

### ISSUE THREAD

**Issue by sgysh** [bytecodealliance/wit-bindgen#660]
src/lib.rs

```
wit_bindgen::generate!({
    world: "host",

    exports: {
        world: MyHost,
    },
});

struct MyHost;

impl Guest for MyHost {
    fn run() {
        print("Hello, world!");
    }
}
```

wit/host.wit

```
package example:host

world host {
  import print: func(msg: string)

  export run: func()
}
```

Cargo.toml

```
[package]
name = "wit-readme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", version = "0.11.0" }
```

```
$ mv wasi_preview1_component_adapter.reactor.wasm wasi_snapshot_preview1.wasm
$ cargo build --target wasm32-wasi
$ wasm-tools component new ./target/wasm32-wasi/debug/wit_readme.wasm -o my-component.wasm --adapt ./wasi_snapshot_preview1.wasm
```

error

```
error: decoding custom section component-type:reactor

Caused by:
    0: component-type version 2 does not match supported version 3
```

version

```
$ cargo --version
cargo 1.72.0 (103a7ff2e 2023-08-15)
$ wasm-tools --version
wasm-tools 1.0.40
```

**Comment by alexcrichton** [comment]
Thanks for the report! That error mesesage probably means that you need to redownload the latest adapters from https://github.com/bytecodealliance/wasmtime/releases/tag/dev (e.g. [this one](https://github.com/bytecodealliance/wasmtime/releases/download/dev/wasi_snapshot_preview1.reactor.wasm)). If you do that does it work out?

**Comment by sachaos** [comment]
@alexcrichton I've got same error because I was using wasi_snapshot_preview1.wasm which was downloaded from old link.
We were able to confirm that it works well by using something hosted in wasmtime.
I've fixed README :)

https://github.com/bytecodealliance/wit-bindgen/pull/661

**Comment by alexcrichton** [comment]
Thanks for that, and glad to hear! I think this is all good so I'm going to close this, but feel free to reopen/comment/etc if more issues come up!

**Comment by sgysh** [comment]
The error was gone. Thank you.
