### ISSUE TITLE
wit-bindgen 0.12 Rust changes how explicitly borrowed param types are borrowed

### ISSUE THREAD

**Issue by rylev** [bytecodealliance/wit-bindgen#673]
Assume the following wit:

```wit
type my-param = string	
my-func: func(param: my-param)
```

If this is code-gened in wit-bindgen Rust 0.11 using `duplicate_if_necessary: true` you get the following signature:

```rust
fn my_func(param: MyParam<'_>)
```

When upgrading to 0.13 however, you get the following:

```rust
fn my_func(param: &MyParam<'_>)
```

Essentially the borrowed param is double borrowed. I would expect that this would not change. [This recent change](https://github.com/bytecodealliance/wit-bindgen/commit/f6004cd10bc7249439da20d9d56deb3808aac86b#diff-d91d041cd6a7e3e16c405fe2fbc3ab6ee6ead9972338e5ac3ebcbd7001741ca1L308) seems to be the culprit.

**Comment by alexcrichton** [comment]
Ah yes the `&& lt.is_none()` change there I think protected against this prior and I removed it as I thought it wasn't necessary. Either that or it was causing compile time issues elsewhere and it still needed to be borrowed, I sort of forget. If you add that back in though it'd be a good starting point to fixing this! You mentioned you were interested in digging in tomorrow and I'm happy to help out and dig further as well with you too
