### ISSUE TITLE
Rust: Support `with` option for `bindgen!` macro.

### ISSUE THREAD

**Issue by fibonacci1729** [bytecodealliance/wit-bindgen#694]
This is already supported in `wasmtime`'s generate macro.

**Comment by fibonacci1729** [comment]
I should have PR for this sometime this week.

**Comment by rvolosatovs** [comment]
Oh, sorry @fibonacci1729 , I was not aware of this issue, did not mean to step on your toes.
We just discussed this with @pchickey 2 days ago at the component model sync.

Could you please review/test #699?

**Comment by fibonacci1729** [comment]
No problem at all! This is great. I'll review and give a test. Thanks!

**Comment by pchickey** [comment]
Sorry Brian! I also didn't see that you were working on this at the time, and nobody corrected me.
