### ISSUE TITLE
reformat wit files

### ISSUE THREAD

**Issue by yamt** [bytecodealliance/wit-bindgen#710]
is there `rustfmt`-like tools for wit files?
otherwise, this is a feature request.

**Comment by Mossaka** [comment]
I am not aware of any formatter for WIT

**Comment by esoterra** [comment]
This would probably be a better question for [`wasm-tools`](https://github.com/bytecodealliance/wasm-tools/)

**Comment by yamt** [comment]
> This would probably be a better question for [`wasm-tools`](https://github.com/bytecodealliance/wasm-tools/)

ok. i filed an issue there. https://github.com/bytecodealliance/wasm-tools/issues/1290

**Comment by yamt** [comment]
moved to https://github.com/bytecodealliance/wasm-tools/issues/1290
