### ISSUE TITLE
Variant with no type payloads generates a C header which is not compatible with C++

### ISSUE THREAD

**Issue by JakeChampion** [bytecodealliance/wit-bindgen#725]
One thing I noticed when using the generated C header files is there is one other situation we need to fix to make c++ compatible.

When a wit variant has no type payloads in any of it's variants, then the generated c bindings will currently contain an empty union, and empty unions have size 0 in C and size 1 in C++.

For example this wit:
```wit
variant header-error {
    invalid-syntax,
    forbidden,
  }
```

Generates this:
```c
typedef struct {
  uint8_t tag;
  union {
  } val;
} wasi_http_0_2_0_rc_2023_11_05_types_header_error_t;

#define WASI_HTTP_0_2_0_RC_2023_11_05_TYPES_HEADER_ERROR_INVALID_SYNTAX 0
#define WASI_HTTP_0_2_0_RC_2023_11_05_TYPES_HEADER_ERROR_FORBIDDEN 1
```

I'm thinking that when wit-bindgen see a wit variant which contains no type payloads, it should treat it the same way it treat wit enums, which is like this:

```wit
enum header-error {
    invalid-syntax,
    forbidden,
  }
```

```c
typedef uint8_t wasi_http_0_2_0_rc_2023_11_05_types_header_error_t;

#define WASI_HTTP_0_2_0_RC_2023_11_05_TYPES_HEADER_ERROR_INVALID_SYNTAX 0
#define WASI_HTTP_0_2_0_RC_2023_11_05_TYPES_HEADER_ERROR_FORBIDDEN 1
```

**Comment by elliottt** [comment]
What do you think about having the code generator instead omit the `union` when no variant constructors have data? That way the codegen strategy would remain largely the same, and if you added variant constructors with data in the future, you wouldn't have as much code to update.
