### ISSUE TITLE
C: why do borrow/own functions have different prefixes?

### ISSUE THREAD

**Issue by yamt** [bytecodealliance/wit-bindgen#727]
```
package foo:bar;

interface hoge {
    resource fuga {
        constructor();
        op: func() -> result;
    }
}

world useless {
    import hoge;
}
```

wit-binden generates code like:
```
// Functions for working with resource `foo:bar/hoge/fuga`
useless_borrow_fuga_t foo_bar_hoge_borrow_fuga(useless_own_fuga_t);
void foo_bar_hoge_fuga_drop_own(useless_own_fuga_t);
extern void useless_fuga_drop_borrow(useless_borrow_fuga_t);
```
i wonder why borrow ones have prefixed with the world and own ones are prefixed with the package/interface.

**Comment by alexcrichton** [comment]
Right now naming like this is unfortunately inconsistent in the C generator and I think there's not a great answer beyond "that's how the code works right now'. This is something I'd like to fix however -- not only this inconsistency but types in general for the C generator which aren't quite as high quality as other generators for example.
