### ISSUE TITLE
Support generics in `wit_bindgen::generate!` macro export types

### ISSUE THREAD

**Issue by tqwewe** [bytecodealliance/wit-bindgen#729]
I am using wit_bindgen in guest rust, and trying to use the `generate!` macro to export a type, however the proc macro panics when the type being exported contains generics.

```rust
wit_bindgen::generate!({
    path: "../wit/foo.wit",
    exports: {
        "foo/instance": Foo<T> // proc macro panicked: not yet implemented: support path arguments
    }
});

pub struct Foo<T> { ... }
```

**Comment by alexcrichton** [comment]
Yes full generics aren't possible here but it can still be fixed to accept a path here instead of identifiers to support something like `Foo<ConcreteType>` or similar.
