### ISSUE TITLE
c generator outputs invalid typedef for wasi-http/proxy 

### ISSUE THREAD

**Issue by JakeChampion** [bytecodealliance/wit-bindgen#735]
When generating bindings for `wasi-http/proxywasi:http/proxy@0.2.0-rc-2023-11-05` I see a generated typedef of:
```c
typedef test_wasi_http_own_request_options_t test_wasi_http_own_request_options_t;
```

I tried to reduce the the definitions down to a smaller set of wit files but whenever I did that, the problem went away.

I've created a github repository which contains the exact wit definitions, wit-bindgen version used and the generated bindings - in the hope that they are helpful in figuring out what is happening.

https://github.com/JakeChampion/wasi-http-wit-bindgen-c

Note: It seems we don't have a consistent c binding generator, each time I run `wit-bindgen c --no-helpers  --world test-wasi-http . --out-dir out` in the above repository I get a different order of output in the built files.

**Comment by alexcrichton** [comment]
Thanks for the report! I hope to get to refactoring C soon and fix both this and a few other related issues

**Comment by Mossaka** [comment]
I can take a look at this issue, as i am currently working on supporting resources in Go
