### ISSUE TITLE
[Rust]: Allow for world dependencies

### ISSUE THREAD

**Issue by rylev** [bytecodealliance/wit-bindgen#742]
Assume the following:

```rust
wit_bindgen::generate!({
    inline: r#"
        package acme:test

        world my_world {
            export wasi:http/incoming-handler@0.2.0-rc-2023-10-18;
        }
    "#,
});
```

I don't believe there is any way to specify how the `wasi:http` package should be resolved. I believe the only possibility to get this to work is copy the world into a `wit` directory and provide all dependencies in the deps folder. 

The `wasmtime::component::bindgen` macro allows specifying `inline` and `path` together where `inline` will be assumed to be the world definition and `path` will be used to resolve dependencies. This is, however, not allowed by `wit_bindgen::generate` macro which fails with the following error:

```
cannot specify second source
```

Should we follow the lead of `wasmtime::component::bindgen` and allow `path` to be used as a way to specify a folder with dependencies or is this behavior in `wasmtime` actually not what we want and we should forge a new path in `wit-bindgen`?

**Comment by alexcrichton** [comment]
Yeah I like the way that Wasmtime ended up here so I think the best thing to do would be to copy Wasmtime's strategy here. Would you be up for implementing this? If not I can also try to give it a stab

**Comment by rylev** [comment]
@alexcrichton I'm back from holiday, and I can try to take this on.
