### ISSUE TITLE
Rust: unused_unsafe in generated code

### ISSUE THREAD

**Issue by morenol** [bytecodealliance/wit-bindgen#752]
I got this clippy failure on generated code

```
2751 |                       unsafe {
     |                       ^^^^^^ unnecessary `unsafe` block
```

**Comment by peterhuene** [comment]
The warning is a result of the Rust code generation from `wit-bindgen-rust`, so I've transferred the issue here.

**Comment by morenol** [comment]
thanks @peterhuene

**Comment by peterhuene** [comment]
I may have already fixed this with https://github.com/bytecodealliance/wit-bindgen/commit/560cf564b0de45187af1cc3feb6036bd0e8950b3, but `cargo-component` hasn't yet updated its dependencies to include the fix.

Do you happen to have a repro case so that I can ensure that updating dependencies to include the fix will also address your issue?

**Comment by morenol** [comment]
```
package my-org:service

interface my-service {
    terminate: func(input: string)
}

world service-guest {
  import my-service
  export run: func(config: string)
}
```

**Comment by peterhuene** [comment]
I've confirmed that this is fixed by the above commit; the next release of cargo-component should prevent the unused unsafe warning.

**Comment by peterhuene** [comment]
I'm going to close the issue as fixed, but if for some reason you still encounter the warning after the next cargo-component release (should be immediately following Wasmtime 15), please reactive and let us know. Thanks for reporting this!

**Comment by peterhuene** [comment]
Also, I'll put up a cargo-component PR in just a few minutes to get the deps updated in main so that if you build cargo-component from source it'll have the fix.
