### ISSUE TITLE
rust-macro: Default Ownership setting should borrow slices of primitives in arguments

### ISSUE THREAD

**Issue by lann** [bytecodealliance/wit-bindgen#769]
The default `ownership: Owning` setting is sufficient for most use cases and generally simpler than `Borrowing`, but necessitates copies in some situations where they aren't strictly necessary. One notable case from wasi is `output-stream`'s `write: func(contents: list<u8>) ...` which generates an argument `contents: Vec<u8>` by default while it is very common (e.g. the `Write` trait) to only have a `&[u8]` at the point where you want to write some data.

@alexcrichton suggested that we could special-case generation for `list<primitive>` function arguments to use `&[T]` instead of `Vec<T>` as a workaround for this problem. This would only apply to top-level argument types (not e.g. record fields), so no separate types would need to be generated.

**Comment by lann** [comment]
Should `string` params get the same treatment (`&str`)?

**Comment by alexcrichton** [comment]
Makes sense to me yeah!

**Comment by lann** [comment]
:facepalm:
