### ISSUE TITLE
c#: projects with `<OutputType>Exe</OutputType>` don't generate `cabi_realloc` when compiled

### ISSUE THREAD

**Issue by jsturtevant** [bytecodealliance/wit-bindgen#778]
Also a further problem I found was that it becomes necessary to declare `<IlcExportUnmanagedEntrypoints>true</IlcExportUnmanagedEntrypoints>` if you have `<OutputType>Exe</OutputType>`, otherwise the compiler won't generate any export for `cabi_realloc` at all and therefore the component wouldn't satisfy the spec.

_Originally posted by @SteveSandersonMS in https://github.com/bytecodealliance/wit-bindgen/issues/760#issuecomment-1835758603_

**Comment by yowl** [comment]
Now we use a separate mechanism for `cabi_realloc` this should be fixed.
