### ISSUE TITLE
What's the use cases for imported `[resource-drop]` function for exported resources?

### ISSUE THREAD

**Issue by Mossaka** [bytecodealliance/wit-bindgen#798]
I noticed that the C bindgen generates `<resource>_drop_own()` function for every imported and exported resources. 

While it is clear to me how the drop works for imported resources, I have a hard time finding use cases for exported resources. In exported resources, we do need to implement a `[dtor]` function to destroy the guest-provided resources. Isn't this enough for the host to drop the resource? 

Appreciate if someone could provide an use case or an example of using C's drop function on exported resources.

**Comment by alexcrichton** [comment]
Some of this may have been cleaned up in https://github.com/bytecodealliance/wit-bindgen/pull/793, but in general if you have an owned handled to your own resource there needs to be a way to drop it. This is for the period of time where a resource is created but hasn't been transferred outside of the component yet.
