### ISSUE TITLE
Example: How to use WASI preview2 in component definitions

### ISSUE THREAD

**Issue by landonxjames** [bytecodealliance/wit-bindgen#801]
I am having trouble understanding the sort of "golden path" for referencing WASI preview 2 types in my WIT component defenitions. 

I have the following wit file:
```wit
package testdemo:component;

interface clients { 
  resource testdemo-client {
    hello-world: func() -> string;
  }
}

world testdemo { 
  export clients;
  include wasi:http/proxy;
}

```

Implemented by the following Rust code:
```rs
wit_bindgen::generate!({
    world: "testdemo",
    exports: {
        "testdemo:component/clients/testdemo-client": TestdemoClients,
     }});
use exports::testdemo::component::clients::GuestTestdemoClient;


pub struct TestdemoClients;

impl GuestTestdemoClient for TestdemoClients {
    fn hello_world(&self) -> String {
        return "Hello World".to_string();
    }
}
```

When attempting to build this code I get the following error:
```sh
error: failed to find package `wasi:http` in `deps` directory
            --> /Volumes/workplace/wasmVersionTests/runtime/wit/component.wit:31:11
             |
          31 |   include wasi:http/proxy;
             |           ^--------
```

And that makes sense, the wit parser doesn't know where to find the `wasi:http` definitions because they aren't linked in in any way.

Where my understanding starts to fail is what is the correct way to link those in? The error message implies they should be in a `dep/` directory on the same level as the `wit/` dir, but am I expected to copy and paste the `wasi:*` wit definitions I need from the WASI Github repo, or is there a more Cargo-ish way to add them as a dependency? Happy to contribute an example of this all working once I figure out what the supported path is!

**Comment by pchickey** [comment]
Yes, right now you need to put the complete set of wasi packages under `wit/deps/`, otherwise wit-bindgen doesn't know how those packages are defined - there is no special treatment given to wasi. For a more automated UX, the `cargo-component` tool automates managing the dependency on wasi, as well as invoking wit-bindgen for the user.

**Comment by landonxjames** [comment]
Got this all figured out and documented here for anyone else trying to figure it out: https://github.com/landonxjames/wasi-http-test
