### ISSUE TITLE
Wasmtime: Shared Tables via wasi_common::table::Table

### ISSUE THREAD

**Issue by theduke** [bytecodealliance/wit-bindgen#81]
I'm working on an Erlang-like runtime that allows sending resources between instances with separate stores, and the current wastime codegen with separate tables for each generated resource complicates our code a lot.

It introduces separate "file descriptor" namespaces between `wasi` and each resource, which then need to be manually mapped back to the actual resource data.

It would be great if a store could stick to using a single table for all resources, eg by using `wasi_common::Table`.

This might also provide some small memory savings due to the single `HashMap` (could become relevant with 100k+ stores and lot's of different resource types).

My immediately proposal would be to just not generate distinct tables, and just expect a `wasi_common::table::Table` instead, which can then be shared at will. The only drawback would be the dynamic downcast overhead from `Any`, but I doubt that would impact performance in any significant way.

An alternative would be to generalize the table behind a trait, but that is additional complexity that is probably not worthwhile.

Happy to implement this myself if the maintainters (@alexcrichton ) are ok with it.

This would obviously be a breaking change for  `witx-wasmtime`.

**Comment by alexcrichton** [comment]
The intention of the wasmtime bindings for resources is that you don't actually deal with indices or anything like that, but rather only actual host objects (validated in the bindings that the indices are all correct). For sharing objects between stores my hope was that the actual host-object itself would be cloneable as either another layer of indirection with indices or something that's like `Rc<Foo>` or something like that. Does that not work for your use case?

Forcing all modules to share the same table isn't really compatible with interface types, which witx-bindgen is targeting. That means that once one module creates a resource all modules magically would get access to it, even though they haven't been granted the resource yet.

**Comment by theduke** [comment]
I have some more thoughts on this, but I'll close this for now since we used a workaround.
