### ISSUE TITLE
Support remapping of interface similar to wasmtime bindgen

### ISSUE THREAD

**Issue by sehz** [bytecodealliance/wit-bindgen#825]
Wasmtime bindgen supports, mapping of interfaces: https://docs.rs/wasmtime/latest/wasmtime/component/macro.bindgen.html.

```
// Remap imported interfaces or resources to types defined in Rust
    // elsewhere. Using this option will prevent any code from being
    // generated for interfaces mentioned here. Resources named here will
    // not have a type generated to represent the resource.
    //
    // Interfaces mapped with this option should be previously generated
    // with an invocation of this macro. Resources need to be mapped to a
    // Rust type name.
    with: {
        "wasi:random/random": some::other::wasi::random::random,
        "wasi:filesystem/types/descriptor": MyDescriptorType,
    },
```

Can we bring this over to here?
This is need to re-use binding across multiple guest

**Comment by greenhat** [comment]
I believe it's already implemented in wit-bindgen. See the test for it at https://github.com/bytecodealliance/wit-bindgen/blob/442f0054fef4a7ff3c7fa59cbce7f9024569c5bc/crates/rust/tests/codegen.rs#L350-L403

**Comment by sehz** [comment]
Does this works with interface from dependencies?  I have something like this:

```
wit_bindgen::generate!({
    world: "myworld",
    exports: {
        world: Component,
        "pkg:test/guest": Component
    },
    with: {
        "pkg:test/myresources/res": common_guest::bindings::pkg::myresources::res::ResourceValue
    }

});
```

And in the dep section. I have wit for `pkg:test/guest` that refers to pkg:test/myresources/res.

```
package pkg:test;

interface guest {

    use myresources.{ res};

    init-resource: func(res: res);

    run: func();
}

world test-world  {
  export guest;
}
```

The guest binding `pkg:test/guest` still using generated `pkg:test/myresources/res` bindings instead of Rust `ResourceValue`

**Comment by fibonacci1729** [comment]
Currently the `with` option in `wit-bindgen` (guest) only supports renaming interfaces (mapping interface id to rust module). It doesn't support the full set of capabilities that `wasmtime` offers (e.g. mapping types / resources to rust code). This would have to be ported over.

**Comment by alexcrichton** [comment]
@sehz when you specify a `with` for `pkg:test/myresources/res` does it work to drop the `/res` and use `pkg:test/myresources` instead? The use cases in Wasmtime motivating thisi feature are a bit different so I'm not sure if it makes sense to bring over the resource-related bits here too.

**Comment by sehz** [comment]
Instead of doing this way, I was advised to have Rust lib (with WIT binding check-in) as direct dep rather than trying to map WIT types.  I will try it and see if that works.   Closing this for now
