### ISSUE TITLE
rust: `with` not working as expected

### ISSUE THREAD

**Issue by rkrishn7** [bytecodealliance/wit-bindgen#832]
Hello,

I'm trying to use the `with` option to reference existing code for wasi interfaces. For example:

```rust
wit_bindgen::generate!(
    world: "my-world",
    exports: {
        world: MyWorld,
    },
    runtime_path: "::my_lib::wit_bindgen::rt",
    with: {
        "wasi:io/error": ::my_lib::wit::wasi::io::error,
        "wasi:io/streams": ::my_lib::wit::wasi::io::streams,
        "wasi:io/poll": ::my_lib::wit::wasi::io::poll,
        "wasi:clocks/monotonic-clock": ::my_lib::wit::wasi::clocks::monotonic_clock,
        "wasi:http/types": ::my_lib::wit::wasi::http::types,
        "wasi:http/outgoing-handler": ::my_lib::wit::wasi::http::outgoing_handler,
    },
);
```

However, this doesn't seem to do what I expect. That is, the generated code includes code for `wasi` instead of aliasing the modules specified in `with`. Note that the same behavior occurs with the CLI.

Please let me know if I can provide any additional context, or if I'm missing something.

Thanks!

**Comment by fibonacci1729** [comment]
Hi @rkrishn7!

I think the issue here is that the interface names you are providing (e.g. `wasi:io/error`)  are not qualified with their versions. I suspect that you are using `wasi-0.2.0` packages which would imply that the interface names are fully described using the version (e.g. `wasi:io/error@0.2.0`, `wasi:io/streams@0.2.0`, etc.). 

Let me know if this is not the case.

**Comment by alexcrichton** [comment]
I thought that this might be the case too (missing versions) where I know Wasmtime's `bindgen!` has a feature where you can drop versions if it's not needed to disambiguate, but [there's a test without versions](https://github.com/bytecodealliance/wit-bindgen/blob/1f4ab0f5587cfccd248d37519b36f9b6a450311c/crates/rust/tests/codegen.rs#L291) as well so I'm not certain.

@rkrishn7 if @fibonacci1729's suggestion doesn't work for you can you provide the sources for how to reproduce this?

**Comment by rkrishn7** [comment]
Thanks @fibonacci1729 @alexcrichton for the feedback!

Yes, it appears I assumed that I can omit the versions. However, including them yields the vague error: `"no entry found for key"`. In my case, it appears that re-mapping a module that contains a type needed by an exported function breaks code generation.

Here's an example world that should help reproduce:

`wit/world.wit`:

```wit
package rkrishn7:wit@0.1.0;

world my-world {
    use wasi:http/types@0.2.0.{incoming-request};

    import wasi:http/outgoing-handler@0.2.0;

    export handle: func(incoming: incoming-request) -> string;
}
```

Here, `handle` depends on `incoming-request` which should be referenced via the re-mapped module.

Using the following command to generate the code:

```bash
RUST_BACKTRACE=1 wit-bindgen rust ./wit --world my-world --exports 'world=MyWorld' --out-dir ./ --runtime-path '::my_lib::wit_bindgen::rt' --with 'wasi:http/types@0.2.0=::my_lib::wit::http::types,wasi:http/outgoing-handler@0.2.0=::my_lib::wit::http::outgoing_handler'
```

returns the following error + backtrace:

```
thread 'main' panicked at crates/rust/src/bindgen.rs:438:70:
no entry found for key
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/option.rs:1988:5
   5: <wit_bindgen_rust::bindgen::FunctionBindgen as wit_bindgen_core::abi::Bindgen>::emit
   6: wit_bindgen_core::abi::Generator<B>::emit
   7: wit_bindgen_core::abi::Generator<B>::lift
   8: wit_bindgen_core::abi::call
   9: wit_bindgen_rust::interface::InterfaceGenerator::generate_guest_export
  10: wit_bindgen_rust::interface::InterfaceGenerator::generate_exports
  11: <wit_bindgen_rust::RustWasm as wit_bindgen_core::WorldGenerator>::export_funcs
  12: wit_bindgen_core::WorldGenerator::generate
  13: wit_bindgen::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sehz** [comment]
Ran into similar obtuse error: `no entry found for key`

**Comment by alexcrichton** [comment]
Thanks for the reproduction! I'll try to dig in today and fix that, it should definitely be a first-class error instead of a Rust panic.

**Comment by rkrishn7** [comment]
> Thanks for the reproduction! I'll try to dig in today and fix that, it should definitely be a first-class error instead of a Rust panic.

@alexcrichton Should my example result in an error? To me, the value of `with` is greatly diminished if `wit_bindgen` can't handle this scenario.

**Comment by alexcrichton** [comment]
I haven't investigated enough to say one way or another. No matter what the generator should never panic, however.

**Comment by alexcrichton** [comment]
Ok I didn't get around to it when I said I'd get around to it but https://github.com/bytecodealliance/wit-bindgen/pull/855 should fix the panic here, and yes this case should work as-is.
