### ISSUE TITLE
Not able to run wasm file created for c example

### ISSUE THREAD

**Issue by PradeepKiruvale** [bytecodealliance/wit-bindgen#834]
Hi,
I have created a `wit` file for host as suggested in the readme and used `wit-bindgen` to create the interface files .h,.c &.o files.
I created the my-component.c as suggested and then created the wasm file.
Used wasm-tools to create the component.

Now I tried running that using wasmr runtime and getting below error

`wasmer my-component.wasm `
error: Unable to compile "my-component.wasm"
╰─▶ 1: Validation error: unknown binary version (at offset 0x4)

Tried even with the wasmedge
`wasmedge my-component.wasm `
[2024-02-09 16:47:04.861] [error] Component model is not fully parsed yet!
[2024-02-09 16:47:04.861] [error] component load is not done yet.

Still I have some issues,

Am I on the right track?. Could you please help me with this?

Thanks,
Pradeep

**Comment by alexcrichton** [comment]
Thanks for the report, but not all runtimes have support for the component model yet. One example runtime that supports the component model is [Wasmtime](https://github.com/bytecodealliance/wasmtime).
