### ISSUE TITLE
rust: Generate an error when a `with` key is not used

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wit-bindgen#841]
There's been some confusion around `with` historically and I know I've typo'd things before. There's a failure mode where if a `with` key isn't used, either because it's configured incorrectly or there's a typo, `wit-bindgen` won't actually generate any warnings or errors and the resulting generated code probably isn't what's expected. This unexpected code generation can lead to surprising error messages down the road too.

Ideally the `wit-bindgen` Rust generator would generate an error message for any configuration in `with` which ended up not being used after all bindings were generated. That could help move the error sooner and perhaps weed out these sorts of errors more quickly.

**Comment by sehz** [comment]
Some more doc would be helpful

**Comment by alexcrichton** [comment]
Fixed in https://github.com/bytecodealliance/wit-bindgen/pull/842, @sehz mind filing a separate issue for improving documentation?

**Comment by sehz** [comment]
Done.  https://github.com/bytecodealliance/wit-bindgen/issues/847
