### ISSUE TITLE
Unable to parse wasi-nn's WITX files

### ISSUE THREAD

**Issue by Michael-F-Bryan** [bytecodealliance/wit-bindgen#85]
I am experimenting with [`wasi-nn`](https://github.com/WebAssembly/wasi-nn) and was having some issues parsing [their WITX file](https://github.com/WebAssembly/wasi-nn/blob/2f59e08aa9972a9ada943feb60730d61d046a782/phases/ephemeral/witx/wasi_ephemeral_nn.witx).

I'm not sure whether this is an issue with their WITX files or the WITX parser used by `witx-bindgen`, or a combination of both, so any suggestions would be appreciated.

---

Steps to reproduce:

```console
$ cargo install --git https://github.com/bytecodealliance/witx-bindgen witx-bindgen-cli --rev f5aa140

$ cd /tmp
$ git clone https://github.com/WebAssembly/wasi-nn
$ cd wasi-nn
$ git rev-parse HEAD
2f59e08aa9972a9ada943feb60730d61d046a782

$ witx-bindgen wasmtime --import phases/ephemeral/witx/wasi_ephemeral_nn.witx --out-dir generated
Error: extra tokens remaining after parse
     --> phases/ephemeral/witx/wasi_ephemeral_nn.witx:13:1
      |
   13 | (typename $buffer_size u32)
      | ^
```

I was able to get past the *"extra tokens remaining after parse"* by wrapping the file's contents in a `module`.

```diff
diff --git a/phases/ephemeral/witx/wasi_ephemeral_nn.witx b/phases/ephemeral/witx/wasi_ephemeral_nn.witx
index 24f7191..e13786e 100644
--- a/phases/ephemeral/witx/wasi_ephemeral_nn.witx
+++ b/phases/ephemeral/witx/wasi_ephemeral_nn.witx
@@ -10,6 +10,7 @@

 ;;; The size of a graph buffer. This is equivalent to `$size` in `typenames.witx` but renamed since `typenames.witx` is
 ;;; not included here but is included in the overall ephemeral phase.
+(module $wasi_ephemeral_nn
 (typename $buffer_size u32)

 ;;; Error codes returned by functions in this API. This is prefixed to avoid conflicts with the `$errno` in
@@ -164,3 +165,4 @@
     (result $error (expected (error $nn_errno)))
   )
 )
+)
```

However, we run into another parse error when declaring `$graph` as an opaque handle.

```
Error: expected an identifier
     --> phases/ephemeral/witx/wasi_ephemeral_nn.witx:77:25
      |
   77 | (typename $graph (handle))
      |                         ^
```

At this point, I'm not sure what changes I might need to make to proceed, or even if I'm going down the right path.

**Comment by peterhuene** [comment]
Those witx files use the "old" syntax and support for it is hidden behind the `old-witx-compat` feature in the `witx2` crate.

Unfortunately it doesn't look like the `witx-bindgen-cli` crate has the feature and properly forwards it to its dependencies to enable the support from the CLI.

I don't know if we intend to properly support the old syntax from the CLI or not, but @alexcrichton would know more.

**Comment by Michael-F-Bryan** [comment]
> I don't think the changes are too invasive to mess up the adaptation code too much.

It looks like [the `Ast::parse_old_witx()` function](https://github.com/hotg-ai/witx-bindgen/blob/160509774b3468f2ccba9b33732c199fa2cd7cef/crates/witx2/src/ast.rs#L175-L379) is the only thing that is broken by reverting to `witx` from crates.io. 

I've made a start on fixing the code but I'm not familiar with the ASTs for `witx` and `witx2` so it's a bit of a learning experience. @alexcrichton, do you know if there is any pre-#11 code that I might be able to copy or look at?

**Comment by alexcrichton** [comment]
Hm I'm not sure, but I ran across this again today so I can also handle doing this in the near future

**Comment by alexcrichton** [comment]
Support for `*.witx` files has now been removed at this point so I'm going to close this.
