### ISSUE TITLE
[dtor] method is gone from the Rust bindings

### ISSUE THREAD

**Issue by cpetig** [bytecodealliance/wit-bindgen#887]
https://github.com/bytecodealliance/wit-bindgen/commit/a0c7383542183d0d9bb60d370477961f8118224a#diff-665b1964a32aa70c9fcedf3844e4c6ba399636be51bcb4d4d3f62faaa280a0a4L1900 removed the generation of the destructor for guest exported resources without a mention in the ChangeLog.

I wonder whether this way of removing exported resources on the guest was intentionally removed or is a bug.

I only found this by accident when creating a new binary with a newer wit-bindgen resulted in missing exported symbols.

**Comment by alexcrichton** [comment]
Ah that's a mistake, I meant to add that to the `export!` macro but I forgot to do so. I'll work on fixing that.

**Comment by alexcrichton** [comment]
> without a mention in the ChangeLog

To clarify, there is no "ChangeLog" file in this repository. I basically do not have time to add that to the things I do as maintenance here.

**Comment by cpetig** [comment]
> > without a mention in the ChangeLog
> 
> To clarify, there is no "ChangeLog" file in this repository. I basically do not have time to add that to the things I do as maintenance here.

Sorry, of course I meant the commit message … which was detailed enough to facilitate this mistake :wink:
