### ISSUE TITLE
rust: How to export all structs

### ISSUE THREAD

**Issue by oovm** [bytecodealliance/wit-bindgen#910]
How to make `wit_bindgen::generate!`  generate all types in `world export <<interface>>`?

Dead code elimination is performed by default. 

If a record or variant is not an input or return value of any function, such a type will not be generated as rust struct and enum.

**Comment by oovm** [comment]
I can try to submit a PR, but I don’t know what should be changed

1. I am going to add allow_unused: bool here

https://github.com/bytecodealliance/wit-bindgen/blob/b4b56c05aab16755ebd495e30bdef767548d766f/crates/guest-rust/macro/src/lib.rs#L263

2. This seems to be the entrance to the backend, but unused has been deleted before.

https://github.com/bytecodealliance/wit-bindgen/blob/b4b56c05aab16755ebd495e30bdef767548d766f/crates/rust/src/interface.rs#L1365

**Comment by alexcrichton** [comment]
I believe the main thing you'll want to change is [this line](https://github.com/bytecodealliance/wit-bindgen/blob/b4b56c05aab16755ebd495e30bdef767548d766f/crates/rust/src/interface.rs#L1332-L1335) where you'll want to consult `self.gen.opts.<your-option-here>`. That'd then be plumbed through the macro in the `enum Opt` you found as well.
