### ISSUE TITLE
The formatting of the files generated by `wit-bindgen tiny-go` is incorrect.

### ISSUE THREAD

**Issue by bkioshn** [bytecodealliance/wit-bindgen#917]
`.go` file generated from `wit-bindgen tiny-go` gave me a format error

```bash
               *failed* | bind-gen-go/host.go:710:46: expected ';', found '-'
               *failed* | bind-gen-go/host.go:716:1: expected 'IDENT', found 'type'
               *failed* | bind-gen-go/host.go:717:1: expected 'IDENT', found 'const'
               *failed* | bind-gen-go/host.go:718:43: expected ')', found '-'
               *failed* | bind-gen-go/host.go:721:1: expected 'IDENT', found 'type'
               *failed* | bind-gen-go/host.go:722:1: expected 'IDENT', found 'const'
               *failed* | bind-gen-go/host.go:723:43: expected ')', found WasiFilesystem0_2_0_TypesOpenFlags
               *failed* | bind-gen-go/host.go:3123:21: expected selector or type assertion, found 'type'
               *failed* | bind-gen-go/host.go:3126:21: expected selector or type assertion, found 'type'
               *failed* | bind-gen-go/host.go:3129:21: expected selector or type assertion, found 'type'
               *failed* | bind-gen-go/host.go:3132:21: expected selector or type assertion, found 'type'
```

In `host.go` (auto generated file), here are some of the line that cause error.
```go
const (
WasiFilesystem0_2_0_TypesDescriptorFlags_READ WasiFilesystem0_2_0_TypesDescriptorFlags = 1 << iota
WasiFilesystem0_2_0_TypesDescriptorFlags_WRITE
WasiFilesystem0_2_0_TypesDescriptorFlags_FILE-INTEGRITY-SYNC
WasiFilesystem0_2_0_TypesDescriptorFlags_DATA-INTEGRITY-SYNC
WasiFilesystem0_2_0_TypesDescriptorFlags_REQUESTED-WRITE-SYNC
WasiFilesystem0_2_0_TypesDescriptorFlags_MUTATE-DIRECTORY
)
```
All the `-` in naming should be replaced with `_`

Here is my `types.wit` where the above is defined
```wit
interface types {
    ....
    flags descriptor-flags {
        read,
        write,
        file-integrity-sync,
        data-integrity-sync,
        requested-write-sync,
        mutate-directory
    }
}
```
Seems like the problem occurs only in `flags`

----

Another problem occurs when using `%`, something like
```wit
 record descriptor-stat {
        /// File type.
        %type: descriptor-type,
        ...
}
```

it generates this in `host.go`
```go
if lift_ret_ptr.type == 0 {
.....
```
which cause this `expected selector or type assertion, found 'type'`

**Comment by Mossaka** [comment]
Thanks for reporting that I am looking into it. May I asked what version of the wit-binden did you use? 

For the second issue, there is [a recent fix](https://github.com/bytecodealliance/wit-bindgen/pull/912) to avoid Go keywords like `type` that just went into the main branch of wit-bindgen. If you could pull the latest commit and build from source, will this issue go away?

**Comment by Mossaka** [comment]
Oh and I think the first issue you encountered has also been fixed https://github.com/bytecodealliance/wit-bindgen/pull/911

**Comment by Mossaka** [comment]
let me know if you are still seeing these issues after you build the CLI from main branch,

**Comment by Mossaka** [comment]
I just made a new relase https://github.com/bytecodealliance/wit-bindgen/releases/tag/v0.24.0 and that should have the fixes for the issues you encountered. Lmk if that works for you

**Comment by bkioshn** [comment]
@Mossaka v0.24.0 solve the problem! Really appreciated your help
