### ISSUE TITLE
Generated Rust code doesn't call `[resource-rep]$resourceName` when converting a resource handle to an internal Rust resource

### ISSUE THREAD

**Issue by dbaeumer** [bytecodealliance/wit-bindgen#933]
Steps to reproduce:

- clone https://github.com/dbaeumer/wit-bindgen-bug.git
- cd into wit-bindgen-bug
- npm install
- npm run build - to build the WebAssembly from Rust
- npm run compile - to compile the TypeScript code

- Run `node ./out/main.js`

Observer: everything works and this is printed to the console
```
Result: 10
```

- open src/main.ts in an editor
- change line 45 from
  ```ts
  const instance = await WebAssembly.instantiate(module, imports);
  ```
  to
  ```ts
  const instance = await WebAssembly.instantiate(module, importsFail);
  ```
- npm run compile

- Run `node ./out/main.js`

Observe: you get 

```
RuntimeError: unreachable
    at __rust_start_panic (wasm://wasm/005ebcba:wasm-function[95]:0x5028)
    at rust_panic (wasm://wasm/005ebcba:wasm-function[93]:0x4ff6)
    at _ZN3std9panicking20rust_panic_with_hook17h9aabd906218897c3E (wasm://wasm/005ebcba:wasm-function[92]:0x4fe8)
    at _ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17h96d2bc381fa6ee1eE (wasm://wasm/005ebcba:wasm-function[81]:0x47ee)
    at _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17ha76513a70bb070b0E (wasm://wasm/005ebcba:wasm-function[80]:0x4754)
    at rust_begin_unwind (wasm://wasm/005ebcba:wasm-function[87]:0x4c77)
    at _ZN4core9panicking9panic_fmt17h3aff855fe938c13fE (wasm://wasm/005ebcba:wasm-function[101]:0x5118)
    at _ZN4core9panicking5panic17h11a2021d92dc1cbbE (wasm://wasm/005ebcba:wasm-function[104]:0x55ca)
    at _ZN4core6option13unwrap_failed17h0e0b231623e0d004E (wasm://wasm/005ebcba:wasm-function[108]:0x58f4)
    at _ZN8resource3bug7exports6vscode7example5types12EngineBorrow3get17h95e782b2af349864E (wasm://wasm/005ebcba:wasm-function[15]:0xb9b)
```

Environment

rustc 1.77.2 (25ef9e3d8 2024-04-09)
wit-bindgen: wit-bindgen-cli 0.24.0

The file bug.rs got generate using the following command `npm run bing-gen`

Things I observed:

- in all cases the export `[export]vscode:example/types#[resource-rep]engine` is not call.
- in the working case `[export]vscode:example/[resource-new]engine` returns the memory address as the handle
- in the fail case I return a handle `1`

It was my understanding from https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#canon-resourcenew that internal memory representation should be converted to handle to identify a resource.

**Comment by alexcrichton** [comment]
Thanks for the report! There's a few things going on here so I'll try to outline a few things at once. First is that you're correct in your understanding that `canon resource.new` returns a handle, not the raw resource representation. That means that as-is `imports` is not a valid implementation of the canonical abi, but `importsFail` is (modulo validation and such). That then leads to the question of why `importsFail` doesn't work in this example.

The next part has to do with a subtelty of i32 and what it means. The return value of `[constructor]engine` is a 32-bit integer which is a resource handle, not a resource representation. This is basically the return value of `[resource-new]engine` in the `importsFail` map. The argument to `[method]engine.execute`, however, is a `borrow` resource which is  exported by the module itself. That hits a special case in the canonical ABI where the resource handle is not passed but instead the raw representation. Effectively the first argument of `[method]engine.execute` should be `h2r.get(handle)`, not `handle`. Once implementing that the example works the same before/after for me locally.

**Comment by dbaeumer** [comment]
@alexcrichton  thanks for the great explanation. Wasn't aware of this :-).

**Comment by alexcrichton** [comment]
`[resource-drop]` will be called whenever a component has an `own` handle that it no longer needs. This can be called for any `own` resource, either imported or exported. There's some validation about when this is ok to do so but beyond that the runtime will then invoke the destructor of the resource from wherever the destructor was defined.

For `[resource-rep]` it's slightly more niche. When a component has an `own` handle to its own exported resource then `[resource-rep]` is used to get the representation. This isn't necessary for `borrow` handles since you're already given the representation automatically.
