### ISSUE TITLE
Import from `host` module

### ISSUE THREAD

**Issue by AlixANNERAUD** [bytecodealliance/wit-bindgen#956]
Hi,
I would like to import this function from the `host` module (native function), as defined in wamr-rust-sdk [here](https://github.com/bytecodealliance/wamr-rust-sdk/blob/269b84460f7b7ef322125c50d3d4454cd0d5139d/src/runtime.rs#L74). Here is my wit code 
```
package host:host;

world host {
  import foo: func(a: f32, b: f32) -> f32;
}
```
But when I look at the generated code, the import is only done from `$root` and not `host` (```rs #[link(wasm_import_module = "$root")]```. Thus, I have to do a search and replace of "$root" with "host" for it to work.
Am I doing it wrong? 
I haven't found any setting regarding importing a "native" module or manually defining the imported module name.

**Comment by alexcrichton** [comment]
Thanks for the report, but I think you're running into a mismatch of systems. WIT is intended for use with components and I don't believe WAMR has support for components, so I don't think you'll be able to use WIT wit WAMR. I believe it's technically possible to achieve what you want here but the impedance mismatch between supporting WIT and not is probably the higher order bit to take care of.
