### ISSUE TITLE
Error: associated function _lift is private

### ISSUE THREAD

**Issue by LUK3ARK** [bytecodealliance/wit-bindgen#962]
Rust

I was stuck on this error for ages and after some trial and error managed to fix it by removing an enum from within a record and replacing it with a boolean, while being imports using 'with' in a child crate.

So, it seems there may be an issue with being able to correctly remap an interface to an interface generated in another package, when that interface contains a record that contains an enum.

I moved passed this by just hacking an approach using a bool

**Comment by LUK3ARK** [comment]
there might have been more to this because it seems fine in another case but it is weird behaviour anyway

**Comment by alexcrichton** [comment]
Are you perhaps using a 0.24.0-or-earlier version of wit-bindgen? I think that https://github.com/bytecodealliance/wit-bindgen/pull/950 should have fixed this and that was released with 0.25.0

**Comment by LUK3ARK** [comment]
This fixed it thanks :)
