### ISSUE TITLE
Relicensing `wit-bindgen` and this repository

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wit-bindgen#987]
# Relicensing `wit-bindgen`

Hello everyone! This issue is here to serve as a checklist for relicensing the `wit-bindgen` repository and all crates that it contains.

* **Before**: `Apache-2.0 WITH LLVM-exception`
* **After**: `Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT`.

In other words this issue is adding two other licensing options to the crate, the Rust standard `Apache-2.0 OR MIT` option. Everyone who has contributed to this repository is cc'd below with a checkbox tracking their approval status.

If you approve of this license change it's requested you leave a comment along the lines of "I approve this license change" and your checkbox will be filled in by a maintainer.

## Why change licenses?

The original choice of `Apache-2.0 WITH LLVM-exception` for this repository matches the licensing decision of Wasmtime itself and was intended to be compatible with it. Some crates in this repository, however, would like to be integrated into upstream Rust itself. For example the `wasmparser` and `wasm-encoder` crates are already part of the Rust compiler. Currently the Rust compiler [has an exception][exception] which allows these crates despite not having the Rust-standard `Apache-2.0 OR MIT` license. The goal of this issue is to make integration in the upstream Rust compiler easier by ensuring that the license is fully compatible with Rust's existing license.

[exception]: https://github.com/rust-lang/rust/blob/d929a42a664c026167800801b26d734db925314f/src/tools/tidy/src/deps.rs#L97-L98

## Contributors

Contributors to `wit-bindgen` are generated with `git shortlog --summary
--numbered --email` as of [7ba0f0359b9c090680f0999b7ec27da7e6dfc825](https://github.com/bytecodealliance/wit-bindgen/commit/7ba0f0359b9c090680f0999b7ec27da7e6dfc825).

* [x] @alexcrichton ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=alexcrichton))
* [x] @dicej ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=dicej))
* [x] @elliottt ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=elliottt))
* [x] @esoterra ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=esoterra))
* [x] @fibonacci1729 ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=fibonacci1729))
* [x] @fitzgen ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=fitzgen))
* [x] @guybedford ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=guybedford))
* [x] @jsturtevant ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=jsturtevant))
* [x] @Liamolucko ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=Liamolucko))
* [x] @Mossaka ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=Mossaka))
* [x] @pchickey ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=pchickey))
* [x] @peterhuene ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=peterhuene))
* [x] @rvolosatovs ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=rvolosatovs))
* [x] @rylev ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=rylev))
* [x] @silesmo ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=silesmo))
* [x] @sunfishcode ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=sunfishcode))
* [x] @thomastaylor312 ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=thomastaylor312))
* [x] @tschneidereit ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=tschneidereit))
* [x] @willemneal ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=willemneal))
* [x] @yowl ([commits](https://github.com/bytecodealliance/wit-bindgen/commits?author=yowl))

## Other contributors

As you can see, we have a long list of contributors to `wit-bindgen`. However,
it's not even the entire list! Lots of other people helped us by providing small
tweaks to the code, fixing grammar issues in documentation, and similar
contributions. While these kinds of contributions are extremely valuable, they
aren't covered by copyrights, and thus we don't require sign-off by the authors
of these contributions.

We do want to use this opportunity to list everyone who contributed to
`wit-bindgen` in whichever way though, so here's the list of people we don't
need sign-off from, including links to their contributions:

* 7sDream [128fd671da6c2d4534dbf59a68eb394b6a8574ed](https://github.com/bytecodealliance/wit-bindgen/commit/128fd671da6c2d4534dbf59a68eb394b6a8574ed) [7b7625a76b141dd34f5b1290deff56f7e78fb631](https://github.com/bytecodealliance/wit-bindgen/commit/7b7625a76b141dd34f5b1290deff56f7e78fb631)
* Ali Somay [262207cb342048c1dbbd28ed9a8280c6bb21578f](https://github.com/bytecodealliance/wit-bindgen/commit/262207cb342048c1dbbd28ed9a8280c6bb21578f)
* Amit Prasad [717ab1eea8572bde8ff09f4d9253f1625e70a69e](https://github.com/bytecodealliance/wit-bindgen/commit/717ab1eea8572bde8ff09f4d9253f1625e70a69e)
* Asraelite [a2f2d54e439c8263d811ba276865bd7ad131c3e6](https://github.com/bytecodealliance/wit-bindgen/commit/a2f2d54e439c8263d811ba276865bd7ad131c3e6)
* Bob Aman [17c45899b8c1a7c7c5d0eae0ba7135f32a1e6edd](https://github.com/bytecodealliance/wit-bindgen/commit/17c45899b8c1a7c7c5d0eae0ba7135f32a1e6edd)
* Christoph Herzog [e165c0226ad0f00a840ef786079b58d0910dbb6b](https://github.com/bytecodealliance/wit-bindgen/commit/e165c0226ad0f00a840ef786079b58d0910dbb6b)
* Daniel Bevenius [f1cf93645ef90a1b8424ae87e2b5e20424719664](https://github.com/bytecodealliance/wit-bindgen/commit/f1cf93645ef90a1b8424ae87e2b5e20424719664) [41f388eec6025e1afbaf613ec384700f8f827115](https://github.com/bytecodealliance/wit-bindgen/commit/41f388eec6025e1afbaf613ec384700f8f827115) [0cc1e99c2682f421d8c81145fb72f13cf28be12a](https://github.com/bytecodealliance/wit-bindgen/commit/0cc1e99c2682f421d8c81145fb72f13cf28be12a)
* David Yamnitsky [01231ec85703fdc18b82b47d2a60f23138c61b1d](https://github.com/bytecodealliance/wit-bindgen/commit/01231ec85703fdc18b82b47d2a60f23138c61b1d)
* DianQK [a79a4be33d76ddf62839ba71602c26a96610ef7c](https://github.com/bytecodealliance/wit-bindgen/commit/a79a4be33d76ddf62839ba71602c26a96610ef7c)
* FrankReh [64fe0239000ba872d59d71adf175ffc344edbdfa](https://github.com/bytecodealliance/wit-bindgen/commit/64fe0239000ba872d59d71adf175ffc344edbdfa)
* FuXiaoHei [40b24bedc693f1319c043f2970ccbcaec8a99fb6](https://github.com/bytecodealliance/wit-bindgen/commit/40b24bedc693f1319c043f2970ccbcaec8a99fb6)
* George Kulakowski [96b4e3f388ef4ddc0c85586794adcb097ce69323](https://github.com/bytecodealliance/wit-bindgen/commit/96b4e3f388ef4ddc0c85586794adcb097ce69323) [f26c887b9f7c61172ebdb2a2e967c8a3f7719765](https://github.com/bytecodealliance/wit-bindgen/commit/f26c887b9f7c61172ebdb2a2e967c8a3f7719765) [a1aabccc836ad3e297cbaaeb503a438ac00a06db](https://github.com/bytecodealliance/wit-bindgen/commit/a1aabccc836ad3e297cbaaeb503a438ac00a06db) [7e9f8787b98c266c25c2c39a2ca4fba3122a796b](https://github.com/bytecodealliance/wit-bindgen/commit/7e9f8787b98c266c25c2c39a2ca4fba3122a796b)
* Gerald Melles [05c8656b56c4835f22d373e5232ba23f5e58c845](https://github.com/bytecodealliance/wit-bindgen/commit/05c8656b56c4835f22d373e5232ba23f5e58c845)
* Jackson Gardner [de91e00e906b932c1f8c5715acd28f52b94fe8b5](https://github.com/bytecodealliance/wit-bindgen/commit/de91e00e906b932c1f8c5715acd28f52b94fe8b5)
* Jackson Hong [2f46ce4cc072107153da0cefe15bdc69aa5b84d0](https://github.com/bytecodealliance/wit-bindgen/commit/2f46ce4cc072107153da0cefe15bdc69aa5b84d0)
* Jacob Hummer [7c9c4626945699efb0379053134f4992d3f36216](https://github.com/bytecodealliance/wit-bindgen/commit/7c9c4626945699efb0379053134f4992d3f36216)
* Jakob Homan [a963df9146b1077f4f0408743d0da36ad7d25c64](https://github.com/bytecodealliance/wit-bindgen/commit/a963df9146b1077f4f0408743d0da36ad7d25c64)
* Jeff Parsons [6dbaa72dc6411c2031512cbe4679cdd57c5eef6d](https://github.com/bytecodealliance/wit-bindgen/commit/6dbaa72dc6411c2031512cbe4679cdd57c5eef6d)
* Jerboas86 [c215ae46f5d2ed022cf982e50e53437d6ce6a568](https://github.com/bytecodealliance/wit-bindgen/commit/c215ae46f5d2ed022cf982e50e53437d6ce6a568)
* Juniper Tyree [a7533653cfc32120ea096bac4ca1bdf94ec1a4bc](https://github.com/bytecodealliance/wit-bindgen/commit/a7533653cfc32120ea096bac4ca1bdf94ec1a4bc)
* Kasper Juul Hermansen [376f0c21f9fa48d7ce843494a23165755501145d](https://github.com/bytecodealliance/wit-bindgen/commit/376f0c21f9fa48d7ce843494a23165755501145d)
* Klim Tsoutsman [3780adcebe733167e1e9186d601d46debe0bc229](https://github.com/bytecodealliance/wit-bindgen/commit/3780adcebe733167e1e9186d601d46debe0bc229) [ea71cad5d7f6355cd7cbdb55e3ce40935d387d2f](https://github.com/bytecodealliance/wit-bindgen/commit/ea71cad5d7f6355cd7cbdb55e3ce40935d387d2f)
* Konstantin Shabanov [45604f58336afaa23a79ed619ef50b69de473688](https://github.com/bytecodealliance/wit-bindgen/commit/45604f58336afaa23a79ed619ef50b69de473688)
* Lann [86401dc72aa872b02a44c7e56064d22d4385b1cb](https://github.com/bytecodealliance/wit-bindgen/commit/86401dc72aa872b02a44c7e56064d22d4385b1cb) [67c7d748cf561ee32e7f52e2d796501e875e4c50](https://github.com/bytecodealliance/wit-bindgen/commit/67c7d748cf561ee32e7f52e2d796501e875e4c50)
* Larry Ewing [e59581bf19f9210b6bd528ee645498cc45e53889](https://github.com/bytecodealliance/wit-bindgen/commit/e59581bf19f9210b6bd528ee645498cc45e53889)
* Mason Ginter [80d9ffaff064092b212bd68339a02e1c2f131416](https://github.com/bytecodealliance/wit-bindgen/commit/80d9ffaff064092b212bd68339a02e1c2f131416)
* Michael Bryan [273947434f9561c3433fbe7aa1103af7613ac9be](https://github.com/bytecodealliance/wit-bindgen/commit/273947434f9561c3433fbe7aa1103af7613ac9be) [f5eed0fb9f1087a2f8889194d0debeeafa789c88](https://github.com/bytecodealliance/wit-bindgen/commit/f5eed0fb9f1087a2f8889194d0debeeafa789c88) [01c8935097c1dd9dcc83badda060f065f3723195](https://github.com/bytecodealliance/wit-bindgen/commit/01c8935097c1dd9dcc83badda060f065f3723195)
* Olaf [6fbcb94ad9ae209b8db6a65fdfb5959ac3de8866](https://github.com/bytecodealliance/wit-bindgen/commit/6fbcb94ad9ae209b8db6a65fdfb5959ac3de8866)
* Oscar Spencer [3597d40b51a86698e932975e7bb54828a2e2054f](https://github.com/bytecodealliance/wit-bindgen/commit/3597d40b51a86698e932975e7bb54828a2e2054f) [d9cf1f0d1123ffda9d2b935078fa7943f8ffb52d](https://github.com/bytecodealliance/wit-bindgen/commit/d9cf1f0d1123ffda9d2b935078fa7943f8ffb52d)
* Paul Colomiets [8c9772f59b1411432eda045179614df41a4acdf9](https://github.com/bytecodealliance/wit-bindgen/commit/8c9772f59b1411432eda045179614df41a4acdf9)
* Philpax [0ab80aedfad3f6b9182f854841c247e93504348a](https://github.com/bytecodealliance/wit-bindgen/commit/0ab80aedfad3f6b9182f854841c247e93504348a)
* Radu M [ab31638ada1703c9ae6a4d5fd30a0927f5869ad0](https://github.com/bytecodealliance/wit-bindgen/commit/ab31638ada1703c9ae6a4d5fd30a0927f5869ad0)
* Raimundo Saona [8f5fffd9ca7e0baee887ba80d0c59146c3dafcfd](https://github.com/bytecodealliance/wit-bindgen/commit/8f5fffd9ca7e0baee887ba80d0c59146c3dafcfd) [5a02e3785a71b74d425e52cde5fb895842704fc2](https://github.com/bytecodealliance/wit-bindgen/commit/5a02e3785a71b74d425e52cde5fb895842704fc2) [1c67f777dad56a2c4d6792952aa551b0b8bddb0e](https://github.com/bytecodealliance/wit-bindgen/commit/1c67f777dad56a2c4d6792952aa551b0b8bddb0e)
* Rajat Jindal [174c5846db7161150f7ea80f3f8904f46b2bda66](https://github.com/bytecodealliance/wit-bindgen/commit/174c5846db7161150f7ea80f3f8904f46b2bda66) [ed26dbf2b85fab3b6e533fa8169ac88cc98f4463](https://github.com/bytecodealliance/wit-bindgen/commit/ed26dbf2b85fab3b6e533fa8169ac88cc98f4463)
* Ramnivas Laddad [57698e6f1b6fa3a1615a457b4e833ab668133142](https://github.com/bytecodealliance/wit-bindgen/commit/57698e6f1b6fa3a1615a457b4e833ab668133142)
* Rohan Krishnaswamy [485d4cc3a2b20efea5080f0a46b1a3078746b92b](https://github.com/bytecodealliance/wit-bindgen/commit/485d4cc3a2b20efea5080f0a46b1a3078746b92b)
* Sammy [e8cd824c8eca92451f863e0d0fb7c9c8cf30fb0c](https://github.com/bytecodealliance/wit-bindgen/commit/e8cd824c8eca92451f863e0d0fb7c9c8cf30fb0c)
* SasakiSaki [b3d53d314a67607846a020fef7bf628311c849d1](https://github.com/bytecodealliance/wit-bindgen/commit/b3d53d314a67607846a020fef7bf628311c849d1)
* Saúl Cabrera [801adea32d9c3e722bf0257d8bec150d73e56d88](https://github.com/bytecodealliance/wit-bindgen/commit/801adea32d9c3e722bf0257d8bec150d73e56d88) [c53fd6988fbd55e80cf6d3ea99e5d24a507e44b8](https://github.com/bytecodealliance/wit-bindgen/commit/c53fd6988fbd55e80cf6d3ea99e5d24a507e44b8) [d086240c74eabae6f225c90c74d705fe10f2d8dc](https://github.com/bytecodealliance/wit-bindgen/commit/d086240c74eabae6f225c90c74d705fe10f2d8dc)
* Stephan Renatus [2c4ec937cab8c23131d644d2fcaf4705a08f9b01](https://github.com/bytecodealliance/wit-bindgen/commit/2c4ec937cab8c23131d644d2fcaf4705a08f9b01)
* Surma [462527127f0d9de935f01e298a7e1c975e124a62](https://github.com/bytecodealliance/wit-bindgen/commit/462527127f0d9de935f01e298a7e1c975e124a62)
* Takumasa Sakao [15907098ddfb8332359d614bb391cbc0d9dd19e9](https://github.com/bytecodealliance/wit-bindgen/commit/15907098ddfb8332359d614bb391cbc0d9dd19e9)
* Teymour Aldridge [d39f9f1ddf7b9a00ecfa4bf7489c3c4831556988](https://github.com/bytecodealliance/wit-bindgen/commit/d39f9f1ddf7b9a00ecfa4bf7489c3c4831556988)
* Victor Adossi [5c684cf569561e7ed04e8b75ed8d973011a80367](https://github.com/bytecodealliance/wit-bindgen/commit/5c684cf569561e7ed04e8b75ed8d973011a80367)
* YAMAMOTO Takashi [5390bab780733f1660d14c254ec985df2816bf1d](https://github.com/bytecodealliance/wit-bindgen/commit/5390bab780733f1660d14c254ec985df2816bf1d)
* Yosh [58ade720598f64db25da4ea0f3cf633333bde89e](https://github.com/bytecodealliance/wit-bindgen/commit/58ade720598f64db25da4ea0f3cf633333bde89e)
* Yuta Saito [1abbfe7301183b01b2621e457123b8f9dc79133d](https://github.com/bytecodealliance/wit-bindgen/commit/1abbfe7301183b01b2621e457123b8f9dc79133d) [67e17745a417d07852cc283d1399d210d4d659cc](https://github.com/bytecodealliance/wit-bindgen/commit/67e17745a417d07852cc283d1399d210d4d659cc)
* bjorn3 [2df2ff28db152eecc896bcc2089a601cc60b72e3](https://github.com/bytecodealliance/wit-bindgen/commit/2df2ff28db152eecc896bcc2089a601cc60b72e3)
* blaine-arcjet [b6c9de7fb0b2dbe753a3e11e9e80863292fa1f0f](https://github.com/bytecodealliance/wit-bindgen/commit/b6c9de7fb0b2dbe753a3e11e9e80863292fa1f0f)
* morenol [1acb079c7556ddddb3187da1fd7eb52f5e134616](https://github.com/bytecodealliance/wit-bindgen/commit/1acb079c7556ddddb3187da1fd7eb52f5e134616)
* nick.kino [2645c4f7ddefa0844a91b214267b1674e45d4884](https://github.com/bytecodealliance/wit-bindgen/commit/2645c4f7ddefa0844a91b214267b1674e45d4884)
* vyta [475ce00220133c8b4c39d52163f3163f224fdc10](https://github.com/bytecodealliance/wit-bindgen/commit/475ce00220133c8b4c39d52163f3163f224fdc10)
* xxchan [70190725949c6f460e49c00880982cefa130354c](https://github.com/bytecodealliance/wit-bindgen/commit/70190725949c6f460e49c00880982cefa130354c)

**Comment by rvolosatovs** [comment]
Sounds great!
I approve this license change

**Comment by fibonacci1729** [comment]
I approve this license change.

**Comment by peterhuene** [comment]
I approve of this license change.

**Comment by tschneidereit** [comment]
For external visibility: this kind of license change requires board approval, as documented in section 4 of the Bytecode Alliance's [IP policy](https://bytecodealliance.org/assets/ip-policy.pdf). The board discussed this back in March and granted the exception.

**Comment by tschneidereit** [comment]
I approve this license change

**Comment by dicej** [comment]
I approve this license change

**Comment by thomastaylor312** [comment]
I approve this license change

**Comment by fitzgen** [comment]
I approve this license change

**Comment by elliottt** [comment]
I approve this license change.

**Comment by sunfishcode** [comment]
I approve this license change.

**Comment by pchickey** [comment]
I approve this license change.

**Comment by esoterra** [comment]
I approve this license change.

**Comment by jsturtevant** [comment]
I approve this license change.

**Comment by Liamolucko** [comment]
I approve this license change.

**Comment by Mossaka** [comment]
I approve this license change

**Comment by rylev** [comment]
I approve this license change

**Comment by silesmo** [comment]
I approve this license change.

**Comment by guybedford** [comment]
I approve this license change.

**Comment by willemneal** [comment]
I approve this license change.

**Comment by yowl** [comment]
I approve this license change
