### ISSUE TITLE
Should the `rust` generator's `--with` CLI option be optional?

### ISSUE THREAD

**Issue by tschneidereit** [bytecodealliance/wit-bindgen#995]
`wit-bindgen rust` currently requires passing the `--with` option. That seems like it might've been an oversight, since it's not clear why that'd always be required.

(Additionally, it seems like different generators use different names for this option. At least, `wit-bindgen c` has the `--rename` option, which serves the same function.)

**Comment by tschneidereit** [comment]
Okay, I think this all stems from #972, which I think didn't quite adjust the CLI enough—unless I'm missing something.

@rylev, it looks like apart from the above issues, the CLI also has no way of specifying that all interfaces should be generated by default.

@alexcrichton would it make sense to introduce some CLI tests that would catch something like this?

**Comment by PI-Victor** [comment]
I'm having the same issue, I want to use wit-bindgen-cli to check in the CI that the WIT file is correct and doesn’t have errors. However, I don’t use any remappings, which forces me to pass random values, causing the CLI to exit with a non-zero code.

**Comment by alexcrichton** [comment]
I opened https://github.com/bytecodealliance/wit-bindgen/pull/999 to improve the situation here. Unfortunately things aren't really set up well to add tests at this time so there's not a great way to prevent regressions at this time.
